import type { CareerRole, CareerSnapshot } from "./types";
import { isOpen, msUntil, urgency } from "./clock";

export const snapshot: CareerSnapshot = {
  updatedAt: "2026-09-09T17:50:00Z",
  thesis:
    "Licensed Hong Kong operator habits plus live AI products. Not a classic PE modeller. The edge is indwelling: ships, then holds the desk.",
  thesisZh:
    "香港持牌运营习惯，加上已经上线的 AI 产品。不是典型 PE 建模手。长处是默会：先做出来，再守住台面。",
};

export const roles: CareerRole[] = [
  {
    id: "B71",
    rank: 1,
    title: "Director, Strategic Investments",
    titleZh: "投资总监",
    org: "Meitu",
    location: "Hong Kong / Shenzhen / Xiamen",
    href: "https://www.meitu.com/en/jobs/",
    closeAt: undefined,
    closeNote: "Posted 24 Aug 2026 · confirm HK seat",
    tier: "ideal",
    bands: ["cvc", "capital"],
    status: "live",
    pay: 5,
    security: 3,
    reputation: 4,
    balance: 3,
    fit: 5,
    rhyme: "The role that named itself. CVC seat next to live AI, China and Hong Kong in one body.",
    rhymeZh: "自己找上门的位子。CVC 坐在能跑的 AI 旁边，中国与香港同一副身体。",
    confirmSeat: true,
    portalOnly: true,
    desk: {
      apply: "Portal first. Job ID 5166696c-9849-4733-aba5-5c144514d716. Confirm Hong Kong seat.",
      draft: "r-4680797737198275177",
      addendum: "LinkedIn note to LIN Lin after portal: r6795721307197991422",
      caution: "Do not email guessed hr@meitu.com.",
    },
  },
  {
    id: "InvestHK",
    rank: 8,
    title: "SVP, Thought Leadership, Marketing and PR (Family Office)",
    titleZh: "高级副总裁 · 家族办公室思想领导与公关",
    org: "InvestHK",
    location: "Hong Kong",
    href: "https://www.investhk.gov.hk/en/careers/senior-vice-president-thought-leadership-marketing-and-pr-family-office_svp022026/",
    closeAt: "2026-09-10T17:00:00+08:00",
    closeNote: "Thu 10 Sep 2026, 5:00 p.m. HK · GF 340 + email",
    tier: "A",
    bands: ["today", "institutions"],
    status: "live",
    pay: 3,
    security: 5,
    reputation: 5,
    balance: 4,
    fit: 3,
    rhyme: "Public-mission Hong Kong. Family-office story, not an AI product seat. Optional skip unless the civic clock matters today.",
    rhymeZh: "香港公共使命。家族办公室叙事，不是 AI 产品席。除非今天的钟有意义。",
    desk: {
      apply: "BOTH GF 340 at csb.gov.hk AND letter+CV to job@investhk.gov.hk",
      draft: "r-929527304975604502",
      caution: "Do not email jasonfong@investhk.gov.hk. English + Putonghua required. Do not claim Cantonese.",
    },
  },
  {
    id: "B76",
    rank: 12,
    title: "Senior Product Manager, Digital Currencies",
    org: "HSBC",
    location: "Central, Hong Kong",
    href: "https://apply.careers.hsbc.com/job/Central-Senior-Product-Manager-Digital-Currencies-Hong/1369854357/",
    closeAt: "2026-09-10T16:00:00Z",
    closeNote: "validThrough Thu 10 Sep 16:00 UTC",
    tier: "B",
    bands: ["today", "capital"],
    status: "live",
    pay: 4,
    security: 5,
    reputation: 5,
    balance: 3,
    fit: 4,
    rhyme: "Digital-asset product next to markets. After the AI solution lead, if the currency seat is the one you want today.",
    rhymeZh: "数字货币产品，贴着市场。先 AI 方案负责人，若今天想要这个货币席。",
    desk: {
      apply: "HSBC Apply. After B4 → B121 then this if still Apply.",
      draft: "r8491470372987069425",
      addendum: "r-6669650216517528312",
    },
  },
  {
    id: "B69",
    rank: 28,
    title: "AVP, Agency Digital Strategy & Development",
    org: "Sun Life",
    location: "Hung Hom, Hong Kong",
    href: "https://sunlife.wd3.myworkdayjobs.com/Experienced-Jobs/job/Hunghom-Kowloon-Hong-Kong/AVP--Agency-Digital-Lead_JR00126149-3",
    closeAt: "2026-09-10T23:59:00+08:00",
    closeNote: "JD posting end 10/09/2026 · treat 10 Sep as binding",
    tier: "B",
    bands: ["today", "capital", "stretch"],
    status: "live",
    pay: 4,
    security: 4,
    reputation: 4,
    balance: 3,
    fit: 2,
    rhyme: "Agency digital, not AI-native building. Fifteen-year stretch. Only if the clock is today.",
    rhymeZh: "代理数字，不是原生 AI 建造。十五年拉伸。只因今天的钟。",
    stretch: true,
    desk: {
      apply: "Workday Experienced-Jobs JR00126149-3",
      draft: "r2323555476074751961",
      addendum: "r8209773115604455947",
    },
  },
  {
    id: "A0",
    rank: 6,
    title: "Senior Manager (Research & Development)",
    org: "HKIC",
    location: "Hong Kong",
    href: "https://www.hkic.org.hk/careers/d1vgj5hkqkfsmy6a0lhsmjpe",
    closeAt: "2026-09-11T17:00:00+08:00",
    closeNote: "Fri 11 Sep 2026, 5:00 p.m. · portal only",
    tier: "A",
    bands: ["today", "institutions"],
    status: "live",
    pay: 4,
    security: 5,
    reputation: 5,
    balance: 4,
    fit: 4,
    rhyme: "Sovereign capital, research desk. Security and reputation at the institutional ceiling.",
    rhymeZh: "主权资本，研究台。安全与名声在机构天花板。",
    portalOnly: true,
    desk: {
      apply: "https://erecruit.hkic.org.hk/ — portal only. Use NEW cover.",
      draft: "r-6787894533467501973",
      caution: "HKIC SAD Investment closed 4 Sep — skip that one.",
    },
  },
  {
    id: "A0b",
    rank: 9,
    title: "Director, Product Development",
    org: "HKMA / CMU OmniClear",
    location: "Hong Kong",
    href: "https://www.hkma.gov.hk/eng/about-us/join-us/current-vacancies/recruit-20260828-4/",
    closeAt: "2026-09-12T23:59:00+08:00",
    closeNote: "Sat 12 Sep 2026",
    tier: "A",
    bands: ["today", "institutions"],
    status: "live",
    pay: 4,
    security: 5,
    reputation: 5,
    balance: 4,
    fit: 4,
    rhyme: "Market-infrastructure product. FMI, not a startup sprint.",
    rhymeZh: "金融基建产品。市场设施，不是创业冲刺。",
    portalOnly: true,
    desk: {
      apply: "https://erecruit.hkma.gov.hk/",
      caution: "Skip OmniClear Director (IT & System Development) vs this product seat.",
    },
  },
  {
    id: "A33",
    rank: 17,
    title: "Senior Manager (Knowledge Transfer) (ORA)",
    titleZh: "高级经理（知识转移）",
    org: "Hong Kong Metropolitan University",
    location: "Hong Kong",
    href: "https://hkmu.taleo.net/careersection/ex_full_time/jobdetail.ftl?job=26001XV&lang=en",
    closeAt: "2026-09-14T23:59:00+08:00",
    closeNote: "Sun 14 Sep 2026, 11:59 p.m. · Taleo 26001XV",
    tier: "A",
    bands: ["today", "institutions", "stretch"],
    status: "live",
    pay: 3,
    security: 5,
    reputation: 4,
    balance: 5,
    fit: 4,
    rhyme: "University knowledge-transfer desk next to angels and incubators. Fifteen years on the JD is a stretch. After PolyU A4.",
    rhymeZh: "大学知识转移台，贴着天使与孵化器。招聘启事上的十五年是拉伸。先 PolyU A4。",
    stretch: true,
    portalOnly: true,
    desk: {
      apply: "HKMU Taleo eRecruitment only. Job 26001XV. Office of Research Affairs and Knowledge Transfer.",
      draft: "r-4774827538237651559",
      caution: "Do not email hrowww@hkmu.edu.hk. English + Chinese including Putonghua. Do not claim Cantonese. Do not invent 15 years.",
    },
  },
  {
    id: "B144",
    rank: 26,
    title: "Senior Manager, Strategic Growth, HK Business",
    org: "HSBC",
    location: "Hong Kong",
    href: "https://apply.careers.hsbc.com/job/Hong-Kong-Senior-Manager-Strategic-Growth-Hong/1363613557/",
    closeAt: "2026-09-12T16:00:00Z",
    closeNote: "validThrough Sat 12 Sep 2026",
    tier: "B",
    bands: ["today", "capital", "stretch"],
    status: "live",
    pay: 4,
    security: 5,
    reputation: 5,
    balance: 3,
    fit: 3,
    rhyme: "CEO Office / Wealth-Mobile-AI strategy. Visibility, not an AI product seat.",
    rhymeZh: "香港行政总裁办公室 / 财富-移动-AI 策略。能见度，不是 AI 产品席。",
    stretch: true,
    desk: {
      apply: "After B4 only if CE Office visibility is the want.",
      draft: "r-89953901072626315",
    },
  },
  {
    id: "A4",
    rank: 7,
    title: "Senior Manager (Entrepreneurship), KTEO",
    org: "PolyU",
    location: "Hung Hom, Hong Kong",
    href: "https://jobs.polyu.edu.hk/job_detail.php?job=260827002",
    closeNote: "Apply Now live 9 Sep · 8 years entrepreneurship / incubation / VC",
    tier: "A",
    bands: ["institutions"],
    status: "live",
    pay: 3,
    security: 5,
    reputation: 5,
    balance: 5,
    fit: 4,
    rhyme: "University entrepreneurship desk. Angel-adjacent, workable hours, CityU path into the other campus.",
    rhymeZh: "大学创业台。贴近天使，工时能过，城大出身走进另一座校园。",
    portalOnly: true,
    desk: {
      apply: "https://jobs.polyu.edu.hk/job_detail.php?job=260827002 — English + Chinese + Putonghua.",
    },
  },
  {
    id: "A4b",
    rank: 18,
    title: "Manager (Temporary), KTEO",
    org: "PolyU",
    location: "Hung Hom, Hong Kong",
    href: "https://jobs.polyu.edu.hk/job_detail.php?job=260721012",
    tier: "A",
    bands: ["institutions"],
    status: "live",
    pay: 2,
    security: 4,
    reputation: 5,
    balance: 5,
    fit: 3,
    rhyme: "Temporary manager beside the entrepreneurship seat. Lower cash, same campus gravity.",
    rhymeZh: "创业席旁边的临时经理。现金较低，同一座校园的引力。",
    portalOnly: true,
    desk: { apply: "https://jobs.polyu.edu.hk/job_detail.php?job=260721012" },
  },
  {
    id: "A21",
    rank: 14,
    title: "Director, Knowledge Transfer and Entrepreneurship Office",
    org: "PolyU",
    location: "Hung Hom, Hong Kong",
    href: "https://jobs.polyu.edu.hk/job_detail.php?job=260827012",
    closeAt: "2026-09-15T00:00:00+08:00",
    closeNote: "Consideration from 15 Sep 2026 until filled",
    tier: "A",
    bands: ["institutions", "stretch"],
    status: "live",
    pay: 4,
    security: 5,
    reputation: 5,
    balance: 4,
    fit: 3,
    rhyme: "Director of the office. Fifteen years / ten years senior management — optional stretch after A4.",
    rhymeZh: "办公室主任。十五年 / 十年高管 —— A4 之后的可选拉伸。",
    stretch: true,
    portalOnly: true,
    desk: {
      apply: "Portal first. Cover r6079673746910716347. Optional nomination to hrstaff@polyu.edu.hk AFTER portal.",
      draft: "r6079673746910716347",
      addendum: "r4273063444403575804 · nomination r-6829610728334285386",
    },
  },
  {
    id: "A1",
    rank: 10,
    title: "Manager, Investor Engagement",
    org: "HKSTP",
    location: "Island East, Hong Kong",
    href: "https://careers.hkstp.org/job/Island-East-Manager%2C-Investor-Engagement-HK-H/1366224266/",
    tier: "A",
    bands: ["institutions", "cvc"],
    status: "live",
    pay: 3,
    security: 4,
    reputation: 4,
    balance: 4,
    fit: 4,
    rhyme: "Investor engagement on the science park. VC/PE/IB/CVC eight years. Do not claim Cantonese.",
    rhymeZh: "科学园的投资人对接。VC/PE/IB/CVC 八年。不要自称粤语。",
    portalOnly: true,
    desk: {
      apply: "HKSTP portal. Cover r3431284342015499835.",
      draft: "r3431284342015499835",
      caution: "Cantonese on JD — do not claim.",
    },
  },
  {
    id: "A30",
    rank: 9,
    title: "Director, AI and Data",
    titleZh: "人工智能与数据总监",
    org: "HKSTP",
    location: "Island East, Hong Kong",
    href: "https://careers.hkstp.org/job/Island-East-Director%2C-AI-and-Data-HK-H/1366190466/",
    closeAt: "2026-09-13T16:00:00Z",
    closeNote: "validThrough Sun 13 Sep 16:00 UTC · 15-year stretch",
    tier: "A",
    bands: ["today", "institutions", "stretch"],
    status: "live",
    pay: 4,
    security: 4,
    reputation: 5,
    balance: 4,
    fit: 4,
    rhyme: "Park-level AI capital. Attract the companies, then hold the cluster. Fifteen years on the JD is a stretch.",
    rhymeZh: "科学园这一层的 AI 资本。把公司吸引来，再守住集群。招聘启事上的十五年是拉伸。",
    stretch: true,
    portalOnly: true,
    desk: {
      apply: "HKSTP Apply Now. Phenom 1366190466. After A1 if the director seat is the want.",
      draft: "r4261511564452071214",
      caution: "Do not email hr@hkstp.org. Cantonese on JD — do not claim. Do not invent 15 AI/DS years.",
    },
  },
  {
    id: "A31",
    rank: 15,
    title: "Chief Digital and Technology Officer",
    titleZh: "首席数字与技术官",
    org: "City University of Hong Kong",
    location: "Kowloon Tong, Hong Kong",
    href: "https://jobs1.cityu.edu.hk/apply/Default.aspx?jobtype=NACAD",
    closeNote: "Ref R/305/26 · until filled · NACAD Apply Now",
    tier: "A",
    bands: ["institutions", "stretch"],
    status: "live",
    pay: 4,
    security: 5,
    reputation: 5,
    balance: 4,
    fit: 3,
    rhyme: "Alma mater. A CIO-class desk, not a CVC seat. The university already knows the name.",
    rhymeZh: "母校。CIO 级台面，不是 CVC 席。学校已经知道这个名字。",
    stretch: true,
    portalOnly: true,
    desk: {
      apply: "jobs1.cityu.edu.hk NACAD Apply Now. Ref R/305/26. LinkedIn 4463824877 is a mirror.",
      draft: "r981486238148765924",
      caution: "Do not email hrojob@cityu.edu.hk. HRO administrative.asp is Incapsula from this desk.",
    },
  },
  {
    id: "A32",
    rank: 16,
    title: "Chief Director, AI Platform & Solutions",
    org: "ASTRI",
    location: "Hong Kong",
    href: "https://careers.astri.org/job/Chief-Director%2C-AI-Platform-%26-Solutions/53997644/",
    closeNote: "Official Apply live 10 Sep · until filled",
    tier: "A",
    bands: ["institutions", "stretch"],
    status: "live",
    pay: 4,
    security: 5,
    reputation: 4,
    balance: 3,
    fit: 3,
    rhyme: "Agentic platform for FinTech and the rest. After the ecosystem manager. Do not invent a PhD.",
    rhymeZh: "给金融科技和其他域用的智能体平台。生态经理之后。不要编博士。",
    stretch: true,
    portalOnly: true,
    desk: {
      apply: "ASTRI Apply Now 53997644. AFTER A22. Do not spray ASTRI engineering clones.",
      draft: "r253940768081559446",
      caution: "15+ years R&D leadership and PhD preferred — optional stretch only.",
    },
  },
  {
    id: "A22",
    rank: 11,
    title: "Senior Manager, Ecosystem and Channel",
    org: "ASTRI",
    location: "Hong Kong",
    href: "https://careers.astri.org/job/Deputy-Director%2C-Ecosystem-and-Channel/56190244/",
    tier: "A",
    bands: ["institutions"],
    status: "live",
    pay: 3,
    security: 5,
    reputation: 4,
    balance: 4,
    fit: 4,
    rhyme: "Applied-science ecosystem. Channel, not a lab coat. Title on the page is Senior Manager.",
    rhymeZh: "应用科学生态。渠道，不是实验袍。页面职称是高级经理。",
    portalOnly: true,
    desk: { apply: "ASTRI Apply Now. URL still says Deputy-Director. Official Apply live 10 Sep. Chief Director AI Platform is A32 after this." },
  },
  {
    id: "A27",
    rank: 13,
    title: "Assistant Director, InnoHK",
    org: "HKSTP",
    location: "Hong Kong",
    href: "https://careers.hkstp.org/",
    tier: "A",
    bands: ["institutions"],
    status: "live",
    pay: 4,
    security: 4,
    reputation: 4,
    balance: 4,
    fit: 4,
    rhyme: "InnoHK cluster. After investor engagement, if the university-collaboration gravity is real.",
    rhymeZh: "InnoHK 集群。投资人对接之后，若大学协作的引力是真的。",
    portalOnly: true,
    desk: { apply: "HKSTP portal. Cover r4210614044772251210 then Manager Uni Collab r-2037962444762767677." },
  },
  {
    id: "B4",
    rank: 5,
    title: "Senior AI Solution Lead",
    org: "HSBC",
    location: "Central, Hong Kong",
    href: "https://apply.careers.hsbc.com/job/Central-Senior-AI-Solution-Lead-Hong/1330173757/",
    closeAt: "2026-09-30T16:00:00Z",
    closeNote: "validThrough Wed 30 Sep",
    tier: "B",
    bands: ["capital"],
    status: "live",
    pay: 5,
    security: 5,
    reputation: 5,
    balance: 3,
    fit: 4,
    rhyme: "Bank AI that has to run. First HSBC gravity well — then commercialization, then currencies.",
    rhymeZh: "银行里必须能跑的 AI。汇丰第一口井 —— 再商业化，再货币。",
    desk: { apply: "HSBC Apply Now. Still live 9 Sep." },
  },
  {
    id: "B146",
    rank: 15,
    title: "AI/ML Design Commercialization Manager, IWPB",
    org: "HSBC",
    location: "Central, Hong Kong",
    href: "https://apply.careers.hsbc.com/job/Central-AI-ML-Design-Commercialization-Manager-International-Wealth-and-Premier-Banking-Hong/1359802857/",
    closeAt: "2026-09-19T16:00:00Z",
    closeNote: "validThrough Sat 19 Sep · GCB 4 · 12-year stretch",
    tier: "B",
    bands: ["capital", "stretch"],
    status: "live",
    pay: 4,
    security: 5,
    reputation: 5,
    balance: 3,
    fit: 3,
    rhyme: "Wealth AI commercialization. After the solution lead. Hands-on analytics bar is a stretch.",
    rhymeZh: "财富 AI 商业化。方案负责人之后。动手分析门槛是拉伸。",
    stretch: true,
    desk: { apply: "After B4 then this then B138.", draft: "r-4207723545408746455" },
  },
  {
    id: "B154",
    rank: 14,
    title: "Head of Alts Investment Solutions, Data and Automation",
    org: "HSBC Global Asset Management",
    location: "Central, Hong Kong",
    href: "https://apply.careers.hsbc.com/job/Central-Head-of-Alts-Investment-Solutions%2C-Data-and-Automation-HSBC-Global-Asset-Management-Hong/1369577357/",
    closeAt: "2026-09-30T16:00:00Z",
    closeNote: "validThrough Wed 30 Sep 16:00 UTC · GCB 4",
    tier: "B",
    bands: ["capital", "stretch"],
    status: "live",
    pay: 5,
    security: 5,
    reputation: 5,
    balance: 3,
    fit: 4,
    rhyme: "Asset-management operations with a data-and-AI mandate. After the AI solution lead. Named alts platforms are a stretch — do not invent eFront.",
    rhymeZh: "资管运营，带着数据与 AI 的任务。先 AI 方案负责人。点名的另类平台是拉伸 —— 不要编造 eFront。",
    stretch: true,
    desk: {
      apply: "HSBC Apply Now. Phenom 1369577357. After B4. Skip Director, Investment Strategy 1371461457 — House View economist, not this ops/AI seat.",
      draft: "r3331028330889342623",
    },
  },
  {
    id: "B138",
    rank: 16,
    title: "Senior Product Manager, Markets & Securities Services",
    org: "HSBC",
    location: "Hong Kong",
    href: "https://apply.careers.hsbc.com/job/Central-Senior-Product-Manager-Markets-Securities-Services-Hong/1367848757/",
    closeAt: "2026-09-18T16:00:00Z",
    closeNote: "validThrough Fri 18 Sep · digital-asset custody",
    tier: "B",
    bands: ["capital"],
    status: "live",
    pay: 4,
    security: 5,
    reputation: 5,
    balance: 3,
    fit: 4,
    rhyme: "Custody product. Digital assets with a bank spine.",
    rhymeZh: "托管产品。数字资产，银行脊骨。",
    desk: { apply: "After B4 → B121 → B76 then this.", draft: "r-6811361595115717280" },
  },
  {
    id: "B6",
    rank: 4,
    title: "SVP, AI Adoption and Commercialization",
    org: "Citi",
    location: "Hong Kong",
    href: "https://jobs.citi.com/job/hong-kong/senior-vice-president-ai-adoption-and-commercialization-senior-lead/287/99751202496",
    closeNote: "Job Req 26990009 · posted 26 Aug 2026",
    tier: "B",
    bands: ["capital"],
    status: "live",
    pay: 5,
    security: 5,
    reputation: 5,
    balance: 3,
    fit: 4,
    rhyme: "Adoption that has to sell inside a bank. Commercialization, not a lab.",
    rhymeZh: "银行内部必须卖得出去的采用。商业化，不是实验室。",
    desk: {
      apply: "Citi portal. Cover r-962642582042496067 + addendum r8039054950086008481.",
      draft: "r-962642582042496067",
    },
  },
  {
    id: "B34",
    rank: 3,
    title: "Applied AI Lead, Executive Director",
    org: "Morgan Stanley",
    location: "Hong Kong",
    href: "https://ms.wd5.myworkdayjobs.com/External",
    tier: "B",
    bands: ["capital"],
    status: "live",
    pay: 5,
    security: 5,
    reputation: 5,
    balance: 3,
    fit: 4,
    rhyme: "Applied AI at a markets house. Reputation ceiling, bank hours.",
    rhymeZh: "市场机构里的应用 AI。名声天花板，银行工时。",
    desk: { apply: "Workday. Cover r2694556748870183470.", draft: "r2694556748870183470" },
  },
  {
    id: "B72",
    rank: 2,
    title: "M&A SA / AD, Portfolio Management, SEA & India",
    org: "Tencent",
    location: "Hong Kong / SEA",
    href: "https://careers.tencent.com/",
    closeNote: "postId 2089180506259374080",
    tier: "cvc",
    bands: ["cvc", "capital"],
    status: "live",
    pay: 5,
    security: 3,
    reputation: 5,
    balance: 3,
    fit: 4,
    rhyme: "Platform CVC. Portfolio as a craft. China-background capital with a Hong Kong desk.",
    rhymeZh: "平台 CVC。组合是手艺。中资背景，香港台面。",
    desk: { apply: "Tencent career postId 2089180506259374080.", draft: "r-2146671588397327289" },
  },
  {
    id: "B36",
    rank: 17,
    title: "Senior Director / Director, AI & Data Strategy",
    org: "Manulife",
    location: "Hong Kong",
    href: "https://manulife.wd3.myworkdayjobs.com/MFCJH_Jobs/job/Hong-Kong/Senior-Director---Director-AI---Data-Strategy---Transformation-Lead_JR26071432",
    closeAt: "2026-09-30T23:59:00+08:00",
    closeNote: "Workday close 30 Sep 2026",
    tier: "B",
    bands: ["capital"],
    status: "live",
    pay: 4,
    security: 4,
    reputation: 4,
    balance: 3,
    fit: 4,
    rhyme: "Asia AI strategy in a life-company. Then digitization (B100), then optional manager (B35).",
    rhymeZh: "寿险公司的亚洲 AI 策略。然后数字化（B100），再可选经理（B35）。",
    desk: {
      apply: "Tenant manulife.wd3.myworkdayjobs.com/MFCJH_Jobs. Cover r5801903241139313616.",
      draft: "r5801903241139313616",
      addendum: "r4654668089183427838",
    },
  },
  {
    id: "B19",
    rank: 19,
    title: "Product Owner — Multi-Asset",
    org: "Fidelity",
    location: "Hong Kong",
    href: "https://fil.wd3.myworkdayjobs.com/001/job/Hong-Kong-Office-New/Product-Owner---Multi-Asset_J69405",
    closeAt: "2026-09-30T23:59:00+08:00",
    closeNote: "Close 30 Sep 2026 · path Hong-Kong-Office-New",
    tier: "B",
    bands: ["capital"],
    status: "live",
    pay: 4,
    security: 4,
    reputation: 5,
    balance: 3,
    fit: 4,
    rhyme: "Multi-asset product owner. Fund craft, not a chatbot seat.",
    rhymeZh: "多元资产产品负责人。基金手艺，不是聊天机器人席。",
    desk: {
      apply: "Workday J69405. Pack r7257447307743357641.",
      draft: "r7257447307743357641",
      addendum: "r4621871729198491241",
    },
  },
  {
    id: "B50",
    rank: 20,
    title: "Senior Manager, APAC Product Owner — Digital Distribution",
    org: "Invesco",
    location: "Hong Kong",
    href: "https://invesco.wd1.myworkdayjobs.com/en-US/IVZ/job/Hong-Kong-Hong-Kong/Senior-Manager--APAC-Product-Owner---Digital-Distribution---Enterprise-Engineering_R-14368",
    tier: "B",
    bands: ["capital"],
    status: "live",
    pay: 4,
    security: 4,
    reputation: 4,
    balance: 3,
    fit: 4,
    rhyme: "Asset-manager digital distribution. After Fidelity, if the product-owner craft is the want.",
    rhymeZh: "资管数字分销。富达之后，若产品负责人手艺是想要的。",
    desk: { apply: "Invesco Workday R-14368." },
  },
  {
    id: "B153",
    rank: 20,
    title: "Associate Director, Distribution Digital",
    org: "AIA",
    location: "Hong Kong, AIA Group Office",
    href: "https://aia.wd3.myworkdayjobs.com/en-US/External/job/Hong-Kong-HK-AIA-Group-Office/Associate-Director--Digital-Agency-Platforms_JR-68436-1",
    closeAt: "2026-09-30T23:59:00+08:00",
    closeNote: "CXS canApply true · endDate 2026-09-30 · slug JR-68436-1",
    tier: "B",
    bands: ["capital", "stretch"],
    status: "live",
    pay: 4,
    security: 4,
    reputation: 4,
    balance: 3,
    fit: 3,
    rhyme: "Agency platforms with AI inside. Group Office, not Macau path. Twelve to fifteen years is a stretch. Then Customer AI.",
    rhymeZh: "代理平台，里面有 AI。集团办公室，不是澳门那条路径。十二到十五年是拉伸。然后才是客户 AI。",
    stretch: true,
    portalOnly: true,
    desk: {
      apply: "Workday External JR-68436-1. Path Hong-Kong-HK-AIA-Group-Office. AFTER B9b, before B117.",
      draft: "r-1064563125725395723",
      caution: "Do not use JR-68436 without -1. Skip JR-69111 Digital Engineering.",
    },
  },
  {
    id: "B117",
    rank: 21,
    title: "Associate Director, Customer AI & Analytics Product Management",
    org: "AIA",
    location: "Hong Kong / Macau",
    href: "https://aia.wd3.myworkdayjobs.com/en-US/External/job/Hong-Kong-HK-AIA-Hong-Kong--Macau/Associate-Director--Customer-AI---Analytics-Product-Management_JR-68056",
    tier: "B",
    bands: ["capital"],
    status: "live",
    pay: 4,
    security: 4,
    reputation: 4,
    balance: 3,
    fit: 4,
    rhyme: "Customer AI product. After Distribution Digital B153. Skip the engineering-strategy clone.",
    rhymeZh: "客户 AI 产品。分销数字之后。跳过工程策略那条克隆。",
    desk: {
      apply: "AIA Workday JR-68056. Path Hong-Kong-HK-AIA-Hong-Kong--Macau.",
      addendum: "r-1766768802526645146",
    },
  },
  {
    id: "B33",
    rank: 22,
    title: "Product Owner, AI in Brand & Marketing",
    org: "Zurich",
    location: "Hong Kong / Singapore / Malaysia",
    href: "https://www.careers.zurich.com/job/Hong-Kong-Product-Owner%2C-AI-in-Brand-%26-Marketing/1368805957/",
    tier: "B",
    bands: ["capital"],
    status: "live",
    pay: 3,
    security: 4,
    reputation: 4,
    balance: 3,
    fit: 4,
    rhyme: "Agentic marketing product. Confirm the Hong Kong seat. Phenom, not Workday.",
    rhymeZh: "代理式营销产品。确认香港席。Phenom，不是 Workday。",
    confirmSeat: true,
    desk: {
      apply: "www.careers.zurich.com Phenom 1368805957. Do not use zurich.wd3.",
      draft: "r-8168033812393573138",
      caution: "CONFIRM HK SEAT. Possible step-down vs Director.",
    },
  },
  {
    id: "B73",
    rank: 23,
    title: "Principal / Senior PM, AI and Agent",
    org: "OKX",
    location: "Hong Kong",
    href: "https://job-boards.greenhouse.io/okx/jobs/7531920003",
    tier: "cvc",
    bands: ["cvc", "capital"],
    status: "live",
    pay: 5,
    security: 2,
    reputation: 3,
    balance: 2,
    fit: 4,
    rhyme: "Agentic product at an exchange. High cash, thinner security and hours. HK right-to-work first.",
    rhymeZh: "交易所的代理产品。现金高，安全与工时更薄。香港工作权优先。",
    desk: {
      apply: "Greenhouse 7531920003. Then optional VP Product 7691999003, then VP AI Strategy 7684888003. Wallet AI is B152 7777029003. Do not spray PM clones. Skip AI Agent Product Expert (Middleware) 7731745003 vs this PM seat.",
    },
  },
  {
    id: "B152",
    rank: 23,
    title: "Principal / Senior PM, AI & Web3 Wallet",
    org: "OKX",
    location: "Hong Kong",
    href: "https://job-boards.greenhouse.io/okx/jobs/7777029003",
    closeNote: "Greenhouse live 10 Sep 2026",
    tier: "cvc",
    bands: ["cvc", "capital"],
    status: "live",
    pay: 5,
    security: 2,
    reputation: 3,
    balance: 2,
    fit: 4,
    rhyme: "Wallet plus agent. After the AI-and-Agent PM, if that is the product you want to hold.",
    rhymeZh: "钱包加上代理。先 AI and Agent 产品经理，若这才是要守的产品。",
    desk: {
      apply: "Greenhouse 7777029003. AFTER B73. Confirm HK seat. Do not spray OKX PM clones.",
      draft: "r-8203520062962774517",
    },
  },
  {
    id: "B149",
    rank: 23,
    title: "Senior Product Manager, Agentic Enablement (Platform AI)",
    org: "Reap",
    location: "Quarry Bay, Hong Kong",
    href: "https://careers.reap.global/jobs/8342685-senior-product-manager-agentic-enablement-platform-ai",
    closeNote: "LinkedIn 4464641446 · posted ~22h ago · official Apply 9 Sep",
    tier: "cvc",
    bands: ["cvc", "capital"],
    status: "live",
    pay: 4,
    security: 2,
    reputation: 3,
    balance: 2,
    fit: 4,
    rhyme: "Hong Kong-headquartered fintech standing up agentic rails. High AI-native fit. Below the bank/university bar for hours and security.",
    rhymeZh: "香港总部的金融科技，在搭代理式轨道。AI 原生贴合高。工时与安全低于银行/大学那条杠。",
    desk: {
      apply: "careers.reap.global 8342685. After OKX B73 if the HK-HQ agentic platform is the want. Skip Reap Engineering Manager AI Agentic vs this PM seat.",
      draft: "r-7528244399176004260",
    },
  },
  {
    id: "B155",
    rank: 26,
    title: "Product Manager",
    org: "HashKey Capital",
    location: "Hong Kong",
    href: "https://hashkey.capital/careers/details44_611.html",
    closeNote: "Official getJobList id 611 · Apply Now to sgrecruitment@hashkey.com",
    tier: "cvc",
    bands: ["cvc", "capital"],
    status: "live",
    pay: 3,
    security: 2,
    reputation: 3,
    balance: 2,
    fit: 4,
    rhyme: "TradFi-and-Web3 fund product. SFC product lifecycle plus AI tools on the JD. PM, not the LinkedIn Product Director.",
    rhymeZh: "传统金融与 Web3 基金产品。持牌产品生命周期，招聘启事上还有 AI 工具。产品经理，不是 LinkedIn 上的产品总监。",
    desk: {
      apply: "Official JD Apply Now: sgrecruitment@hashkey.com. details44_611.html. After bank/university. Do not also spray Product Manager/Specialist 593.",
      draft: "r2852953938224944669",
      caution:
        "LinkedIn Product Director 4463321930 is not on official getJobList (ids 694, 692, 613, 612, 611, 593, 454, 445). Do not apply via LinkedIn-only. Skip Risk Director 612 vs AI-native builder. Skip BD Manager 454 vs this product seat.",
    },
  },
  {
    id: "B150",
    rank: 24,
    title: "Senior Product Manager — TradFi Wealth",
    org: "Binance",
    location: "Hong Kong / Remote",
    href: "https://jobs.lever.co/binance/1c3e9e01-82b8-4840-85b1-82cabd86bcfd",
    closeNote: "Lever Apply 9 Sep · confirm Hong Kong seat vs Remote",
    tier: "cvc",
    bands: ["cvc", "capital"],
    status: "live",
    pay: 5,
    security: 2,
    reputation: 3,
    balance: 2,
    fit: 4,
    rhyme: "TradFi wealth product on an exchange. Trading and asset-management habits meet a live product seat. Confirm Hong Kong. Do not spray Binance PM clones.",
    rhymeZh: "交易所上的传统金融财富产品。交易与资管习惯碰上产品席。确认香港。不要群发币安产品克隆。",
    confirmSeat: true,
    desk: {
      apply: "jobs.lever.co/binance/1c3e9e01-82b8-4840-85b1-82cabd86bcfd. Then optional AI Agent & Harness. Skip Stock Trading AM vs this wealth seat. Skip accelerator/junior.",
      draft: "r2859635877950117754",
    },
  },
  {
    id: "B151",
    rank: 25,
    title: "Product Manager, AI Agent & Harness",
    org: "Binance",
    location: "Hong Kong / Remote",
    href: "https://jobs.lever.co/binance/0a03c5e3-4a06-4aa7-8c06-25a473ceeb33",
    closeNote: "Lever Apply 9 Sep · after B150 only",
    tier: "cvc",
    bands: ["cvc"],
    status: "live",
    pay: 4,
    security: 2,
    reputation: 3,
    balance: 2,
    fit: 4,
    rhyme: "Agent harness product. After TradFi wealth, only if the agent seat is the one you want. Do not also spray chatbot / search PM clones.",
    rhymeZh: "代理挽具产品。传统金融财富之后，只若这个代理席是想要的。不要再群发聊天机器人/搜索克隆。",
    desk: {
      apply: "jobs.lever.co/binance/0a03c5e3-4a06-4aa7-8c06-25a473ceeb33. AFTER B150. Skip AI Chatbot PM and AI Search contract.",
      draft: "r-8111998692901901578",
    },
  },
  {
    id: "B113",
    rank: 27,
    title: "Product Lead – AI Investing",
    org: "BJAK",
    location: "Hong Kong",
    href: "https://jobs.ashbyhq.com/bjakcareer/c3e6469e-684d-4ecd-843a-ce3f7da8cf4d",
    tier: "cvc",
    bands: ["cvc", "stretch"],
    status: "live",
    pay: 4,
    security: 2,
    reputation: 2,
    balance: 1,
    fit: 4,
    rhyme: "AI investing product. Below the bank/university bar for hours. One vertical only — do not spray clones.",
    rhymeZh: "AI 投资产品。工时低于银行/大学那条杠。只选一条垂类 —— 不要群发克隆。",
    stretch: true,
    desk: {
      apply: "Ashby. Then optional TPM stockbroking, then Head of Strategy. Pick one vertical.",
      caution: "JD says not counting hours.",
    },
  },
  {
    id: "B110",
    rank: 24,
    title: "Innovation Manager – Product Management",
    org: "BOCHK",
    location: "Hong Kong",
    href: "https://careers.pageuppeople.com/798/cw/en/job/500073",
    tier: "B",
    bands: ["capital"],
    status: "live",
    pay: 4,
    security: 5,
    reputation: 4,
    balance: 3,
    fit: 4,
    rhyme: "Bank innovation with a product-management name. Then digital strategy 500080.",
    rhymeZh: "银行创新，名字叫产品管理。然后数字策略 500080。",
    desk: { apply: "PageUp 500073 still Apply 9 Sep. Then 500080." },
  },
  {
    id: "B40b",
    rank: 25,
    title: "AVP, ETP Product",
    org: "HKEX",
    location: "Hong Kong",
    href: "https://hkex.wd3.myworkdayjobs.com/HKEXCareerPage",
    closeNote: "R004400 canApply true 9 Sep · Group Strategy R004123 slug 404",
    tier: "B",
    bands: ["capital", "institutions"],
    status: "live",
    pay: 4,
    security: 5,
    reputation: 5,
    balance: 3,
    fit: 3,
    rhyme: "Exchange-traded product. Market infrastructure with a product name.",
    rhymeZh: "交易所买卖产品。市场基建，带着产品的名字。",
    desk: {
      apply: "HKEXCareerPage R004400. Do not apply Group Strategy R004123 slug — 404.",
    },
  },
  {
    id: "A25",
    rank: 29,
    title: "Manager, Investment (HK)",
    org: "The Mills Fabrica",
    location: "Hong Kong",
    href: "https://www.themillsfabrica.com/careers/manager-investment-hk/",
    closeNote: "Posted 29 Apr 2026",
    tier: "A",
    bands: ["cvc", "institutions"],
    status: "live",
    pay: 3,
    security: 3,
    reputation: 3,
    balance: 4,
    fit: 4,
    rhyme: "Climate/fashion CVC. Angel-adjacent. Do not email the general contact as if it were HR.",
    rhymeZh: "气候/时尚 CVC。贴近天使。不要把总邮箱当成 HR。",
    desk: {
      apply: "Listing only. contact@themillsfabrica.com is general contact, not a job-apply instruction.",
      caution: "Do not guess HR.",
    },
  },
];

export type FieldFilter = "all" | "today" | "institutions" | "capital" | "cvc" | "stretch";

export function inField(role: CareerRole, filter: FieldFilter, now = new Date()): boolean {
  if (role.status === "skip") return false;
  if (filter === "all") return true;
  if (filter === "today") {
    return role.bands.includes("today") && isOpen(role.closeAt, now);
  }
  return role.bands.includes(filter);
}

export function sortField(list: CareerRole[], now = new Date()): CareerRole[] {
  return [...list].sort((a, b) => {
    const ua = urgency(a.closeAt, now);
    const ub = urgency(b.closeAt, now);
    const order = { now: 0, soon: 1, week: 2, open: 3 };
    if (order[ua] !== order[ub]) return order[ua] - order[ub];
    if (a.tier === "ideal" && b.tier !== "ideal") return -1;
    if (b.tier === "ideal" && a.tier !== "ideal") return 1;
    const am = a.closeAt ? msUntil(a.closeAt, now) : Number.POSITIVE_INFINITY;
    const bm = b.closeAt ? msUntil(b.closeAt, now) : Number.POSITIVE_INFINITY;
    if (am !== bm) return am - bm;
    return a.rank - b.rank;
  });
}

export function nextMoves(now = new Date()): CareerRole[] {
  const open = roles.filter((r) => r.status === "live" && isOpen(r.closeAt, now));
  const today = sortField(
    open.filter((r) => r.bands.includes("today") || r.tier === "ideal"),
    now,
  );
  const rest = sortField(
    open.filter((r) => !today.includes(r)),
    now,
  );
  return [...today, ...rest].slice(0, 8);
}
