import type { CareerRole, CareerSnapshot } from "./types";
import { isOpen, msUntil, urgency } from "./clock";

export const snapshot: CareerSnapshot = {
  updatedAt: "2026-09-09T21:40:00Z",
  thesis:
    "Licensed Hong Kong IM / Director / OMO / RO at a China top-15 quantitative fund, founder-executive of live AI products, and operator of an offshore hedge trading book since Sep 2025. Not a classic PE modeller. The edge is indwelling: ships, then holds the desk.",
  thesisZh:
    "香港持牌投资经理 / 董事 / 整体管理监督 / 负责人员，任职中国头部十五量化基金；同时是已上线 AI 产品的创始人兼执行董事，并自 2025 年 9 月起运营离岸对冲交易账簿。不是典型 PE 建模手。长处是默会：先做出来，再守住台面。",
};

export const roles: CareerRole[] = [
  {
    id: "B71",
    rank: 1,
    title: "Director, Strategic Investments",
    titleZh: "投资总监",
    org: "Meitu",
    location: "Hong Kong / Shenzhen / Xiamen",
    href: "https://www.meitu.com/en/jobs/",
    closeAt: undefined,
    closeNote: "Posted 24 Aug 2026 · confirm HK seat",
    tier: "ideal",
    bands: ["cvc", "capital"],
    status: "live",
    pay: 5,
    security: 3,
    reputation: 4,
    balance: 3,
    fit: 5,
    rhyme: "The role that named itself. CVC seat next to live AI, China and Hong Kong in one body.",
    rhymeZh: "自己找上门的位子。CVC 坐在能跑的 AI 旁边，中国与香港同一副身体。",
    confirmSeat: true,
    portalOnly: true,
    desk: {
      apply: "Portal first. Job ID 5166696c-9849-4733-aba5-5c144514d716. Confirm Hong Kong seat.",
      draft: "r-4680797737198275177",
      addendum: "LinkedIn note to LIN Lin after portal: r6795721307197991422",
      caution: "Do not email guessed hr@meitu.com. Official Visa Senior Director Innovation & Partnerships REF083278W is B162 after this if partnerships is the want.",
    },
  },
  {
    id: "B162",
    rank: 4,
    title: "Senior Director, Innovation and Strategic Partnerships",
    org: "Visa",
    location: "Hong Kong",
    href: "https://visa.wd5.myworkdayjobs.com/Visa/job/HK---Hong-Kong-China/Senior-Director--Innovation-and-Strategic-Partnerships--Hong-Kong_REF083278W",
    closeNote: "Workday Visa tenant · canApply true · posted 30+ days · no endDate",
    tier: "B",
    bands: ["cvc", "capital", "stretch"],
    status: "live",
    pay: 5,
    security: 4,
    reputation: 5,
    balance: 3,
    fit: 3,
    rhyme: "Hong Kong innovation partnerships next to live products. After Meitu. Fifteen years and fluent Cantonese are stretches — do not invent either.",
    rhymeZh: "香港创新与生态合作。美图之后。十五年与粤语都是拉伸 —— 不要编。",
    stretch: true,
    portalOnly: true,
    desk: {
      apply: "Official Workday visa.wd5 /Visa REF083278W. HK - Hong Kong, China. canApply true.",
      draft: "r-2983781475055829866",
      caution: "15+ years. Fluent English, Cantonese and Mandarin on JD — do not claim Cantonese. Skip Director Client Consulting CMS/Stablecoin/AI REF083051W (consulting origination). Skip Director FP&A REF085112W.",
    },
  },
  {
    id: "InvestHK",
    rank: 8,
    title: "SVP, Thought Leadership, Marketing and PR (Family Office)",
    titleZh: "高级副总裁 · 家族办公室思想领导与公关",
    org: "InvestHK",
    location: "Hong Kong",
    href: "https://www.investhk.gov.hk/en/careers/senior-vice-president-thought-leadership-marketing-and-pr-family-office_svp022026/",
    closeAt: "2026-09-10T17:00:00+08:00",
    closeNote: "Thu 10 Sep 2026, 5:00 p.m. HK · GF 340 + email · official page live 9 Sep 21:40 UTC"
    tier: "A",
    bands: ["today", "institutions"],
    status: "live",
    pay: 3,
    security: 5,
    reputation: 5,
    balance: 4,
    fit: 3,
    rhyme: "Public-mission Hong Kong. Family-office story, not an AI product seat. Optional skip unless the civic clock matters today.",
    rhymeZh: "香港公共使命。家族办公室叙事，不是 AI 产品席。除非今天的钟有意义。",
    desk: {
      apply: "BOTH GF 340 at csb.gov.hk AND letter+CV to job@investhk.gov.hk",
      draft: "r-929527304975604502",
      caution: "Do not email jasonfong@investhk.gov.hk. English + Putonghua required. Do not claim Cantonese.",
    },
  },
  {
    id: "B76",
    rank: 12,
    title: "Senior Product Manager, Digital Currencies",
    org: "HSBC",
    location: "Central, Hong Kong",
    href: "https://apply.careers.hsbc.com/job/Central-Senior-Product-Manager-Digital-Currencies-Hong/1369854357/",
    closeAt: "2026-09-10T16:00:00Z",
    closeNote: "validThrough Thu 10 Sep 16:00 UTC · Apply now rechecked 9 Sep 21:40 UTC"
    tier: "B",
    bands: ["today", "capital"],
    status: "live",
    pay: 4,
    security: 5,
    reputation: 5,
    balance: 3,
    fit: 4,
    rhyme: "Digital-asset product next to markets. After the AI solution lead, if the currency seat is the one you want today.",
    rhymeZh: "数字货币产品，贴着市场。先 AI 方案负责人，若今天想要这个货币席。",
    desk: {
      apply: "HSBC Apply. After B4 → B121 then this if still Apply.",
      draft: "r8491470372987069425",
      addendum: "r-6669650216517528312",
    },
  },
  {
    id: "B69",
    rank: 28,
    title: "AVP, Agency Digital Strategy & Development",
    org: "Sun Life",
    location: "Hung Hom, Hong Kong",
    href: "https://sunlife.wd3.myworkdayjobs.com/Experienced-Jobs/job/Hunghom-Kowloon-Hong-Kong/AVP--Agency-Digital-Lead_JR00126149-3",
    closeAt: "2026-09-10T23:59:00+08:00",
    closeNote: "JD posting end 10/09/2026 · treat 10 Sep as binding · CXS canApply true rechecked 9 Sep 21:40 UTC · endDate 11 Sep 2026"
    tier: "B",
    bands: ["today", "capital", "stretch"],
    status: "live",
    pay: 4,
    security: 4,
    reputation: 4,
    balance: 3,
    fit: 2,
    rhyme: "Agency digital, not AI-native building. Fifteen-year stretch. Only if the clock is today.",
    rhymeZh: "代理数字，不是原生 AI 建造。十五年拉伸。只因今天的钟。",
    stretch: true,
    desk: {
      apply: "Workday Experienced-Jobs JR00126149-3",
      draft: "r2323555476074751961",
      addendum: "r8209773115604455947",
    },
  },
  {
    id: "A0",
    rank: 6,
    title: "Senior Manager (Research & Development)",
    org: "HKIC",
    location: "Hong Kong",
    href: "https://www.hkic.org.hk/careers/d1vgj5hkqkfsmy6a0lhsmjpe",
    closeAt: "2026-09-11T17:00:00+08:00",
    closeNote: "Fri 11 Sep 2026, 5:00 p.m. · portal only",
    tier: "A",
    bands: ["today", "institutions"],
    status: "live",
    pay: 4,
    security: 5,
    reputation: 5,
    balance: 4,
    fit: 4,
    rhyme: "Sovereign capital, research desk. Security and reputation at the institutional ceiling.",
    rhymeZh: "主权资本，研究台。安全与名声在机构天花板。",
    portalOnly: true,
    desk: {
      apply: "https://erecruit.hkic.org.hk/ — portal only. Use NEW cover.",
      draft: "r-6787894533467501973",
      caution: "HKIC SAD Investment closed 4 Sep — skip that one.",
    },
  },
  {
    id: "A0b",
    rank: 9,
    title: "Director, Product Development",
    org: "HKMA / CMU OmniClear",
    location: "Hong Kong",
    href: "https://www.hkma.gov.hk/eng/about-us/join-us/current-vacancies/recruit-20260828-4/",
    closeAt: "2026-09-12T23:59:00+08:00",
    closeNote: "Sat 12 Sep 2026",
    tier: "A",
    bands: ["today", "institutions"],
    status: "live",
    pay: 4,
    security: 5,
    reputation: 5,
    balance: 4,
    fit: 4,
    rhyme: "Market-infrastructure product. FMI, not a startup sprint.",
    rhymeZh: "金融基建产品。市场设施，不是创业冲刺。",
    portalOnly: true,
    desk: {
      apply: "https://erecruit.hkma.gov.hk/",
      caution:
        "Skip OmniClear Director (IT & System Development) recruit-20260828-5 (12 Sep): 8 years IT leadership + 3 years custody/fund admin, CS degree, Cantonese, SWIFT/SQL — A0c. Skip Executive Director (IT & System Development) recruit-20260904-3 (19 Sep): 10 years IT architecture, mainframe-to-modular, post-trade, Cantonese — A0d. Product Development stays the OmniClear seat.",
    },
  },
  {
    id: "A33",
    rank: 17,
    title: "Senior Manager (Knowledge Transfer) (ORA)",
    titleZh: "高级经理（知识转移）",
    org: "Hong Kong Metropolitan University",
    location: "Hong Kong",
    href: "https://hkmu.taleo.net/careersection/ex_full_time/jobdetail.ftl?job=26001XV&lang=en",
    closeAt: "2026-09-14T23:59:00+08:00",
    closeNote: "Sun 14 Sep 2026, 11:59 p.m. · Taleo 26001XV",
    tier: "A",
    bands: ["today", "institutions", "stretch"],
    status: "live",
    pay: 3,
    security: 5,
    reputation: 4,
    balance: 5,
    fit: 4,
    rhyme: "University knowledge-transfer desk next to angels and incubators. Fifteen years on the JD is a stretch. After PolyU A4.",
    rhymeZh: "大学知识转移台，贴着天使与孵化器。招聘启事上的十五年是拉伸。先 PolyU A4。",
    stretch: true,
    portalOnly: true,
    desk: {
      apply: "HKMU Taleo eRecruitment only. Job 26001XV. Office of Research Affairs and Knowledge Transfer.",
      draft: "r-4774827538237651559",
      caution:
        "Do not email hrowww@hkmu.edu.hk. English + Chinese including Putonghua. Do not claim Cantonese. Do not invent 15 years. Skip sibling Assistant Director (Mainland Research Development) OSI 26001FP — Taleo close was 13 Jul 2026.",
    },
  },
  {
    id: "B144",
    rank: 26,
    title: "Senior Manager, Strategic Growth, HK Business",
    org: "HSBC",
    location: "Hong Kong",
    href: "https://apply.careers.hsbc.com/job/Hong-Kong-Senior-Manager-Strategic-Growth-Hong/1363613557/",
    closeAt: "2026-09-12T16:00:00Z",
    closeNote: "validThrough Sat 12 Sep 2026",
    tier: "B",
    bands: ["today", "capital", "stretch"],
    status: "live",
    pay: 4,
    security: 5,
    reputation: 5,
    balance: 3,
    fit: 3,
    rhyme: "CEO Office / Wealth-Mobile-AI strategy. Visibility, not an AI product seat.",
    rhymeZh: "香港行政总裁办公室 / 财富-移动-AI 策略。能见度，不是 AI 产品席。",
    stretch: true,
    desk: {
      apply: "After B4 only if CE Office visibility is the want.",
      draft: "r-89953901072626315",
    },
  },
  {
    id: "A4",
    rank: 7,
    title: "Senior Manager (Entrepreneurship), KTEO",
    org: "PolyU",
    location: "Hung Hom, Hong Kong",
    href: "https://jobs.polyu.edu.hk/job_detail.php?job=260827002",
    closeNote: "Consideration from 3 Sep 2026 until filled · written test · Rechecked Apply Now 9 Sep 20:15 UTC",
    tier: "A",
    bands: ["institutions"],
    status: "live",
    pay: 3,
    security: 5,
    reputation: 5,
    balance: 5,
    fit: 4,
    rhyme: "University entrepreneurship desk. Angel-adjacent, workable hours, CityU path into the other campus.",
    rhymeZh: "大学创业台。贴近天使，工时能过，城大出身走进另一座校园。",
    portalOnly: true,
    desk: {
      apply: "PolyU Apply Now 260827002-IE. English + Chinese + fluency in Putonghua. After this, optional A21 Director — official slug live again, consideration from 15 Sep.",
      draft: "r3271210062041871589",
      caution: "Do not email hrstaff@polyu.edu.hk for this SM seat. That mailbox is A21 nominations after portal. Do not claim Cantonese. Do not invent a university incubator GM decade.",
    },
  },
  {
    id: "A4b",
    rank: 18,
    title: "Manager (Temporary), KTEO",
    org: "PolyU",
    location: "Hung Hom, Hong Kong",
    href: "https://jobs.polyu.edu.hk/job_detail.php?job=260721012",
    tier: "A",
    bands: ["institutions"],
    status: "live",
    pay: 2,
    security: 4,
    reputation: 5,
    balance: 5,
    fit: 3,
    rhyme: "Temporary manager beside the entrepreneurship seat. Lower cash, same campus gravity.",
    rhymeZh: "创业席旁边的临时经理。现金较低，同一座校园的引力。",
    portalOnly: true,
    desk: { apply: "https://jobs.polyu.edu.hk/job_detail.php?job=260721012" },
  },
  {
    id: "A21",
    rank: 14,
    title: "Director, Knowledge Transfer and Entrepreneurship Office",
    org: "PolyU",
    location: "Hung Hom, Hong Kong",
    href: "https://jobs.polyu.edu.hk/job_detail.php?job=260827012",
    closeAt: "2026-09-15T00:00:00+08:00",
    closeNote: "Consideration from 15 Sep 2026 until filled · Rechecked Apply Now 9 Sep 20:15 UTC (slug was 404 last pass)",
    tier: "A",
    bands: ["institutions", "stretch"],
    status: "live",
    pay: 4,
    security: 5,
    reputation: 5,
    balance: 4,
    fit: 3,
    rhyme: "Director of the office. Fifteen years / ten years senior management — optional stretch after A4.",
    rhymeZh: "办公室主任。十五年 / 十年高管 —— A4 之后的可选拉伸。",
    stretch: true,
    portalOnly: true,
    desk: {
      apply: "Portal first. Cover r6079673746910716347. Optional nomination to hrstaff@polyu.edu.hk AFTER portal.",
      draft: "r6079673746910716347",
      addendum: "r4273063444403575804 · nomination r-6829610728334285386",
    },
  },
  {
    id: "A1",
    rank: 10,
    title: "Manager, Investor Engagement",
    org: "HKSTP",
    location: "Island East, Hong Kong",
    href: "https://careers.hkstp.org/job/Island-East-Manager%2C-Investor-Engagement-HK-H/1366224266/",
    tier: "A",
    bands: ["institutions", "cvc"],
    status: "live",
    pay: 3,
    security: 4,
    reputation: 4,
    balance: 4,
    fit: 4,
    rhyme: "Investor engagement on the science park. VC/PE/IB/CVC eight years. Do not claim Cantonese.",
    rhymeZh: "科学园的投资人对接。VC/PE/IB/CVC 八年。不要自称粤语。",
    portalOnly: true,
    desk: {
      apply: "HKSTP portal. Cover r3431284342015499835.",
      draft: "r3431284342015499835",
      caution: "Cantonese on JD — do not claim.",
    },
  },
  {
    id: "A30",
    rank: 9,
    title: "Director, AI and Data",
    titleZh: "人工智能与数据总监",
    org: "HKSTP",
    location: "Island East, Hong Kong",
    href: "https://careers.hkstp.org/job/Island-East-Director%2C-AI-and-Data-HK-H/1366190466/",
    closeAt: "2026-09-13T16:00:00Z",
    closeNote: "validThrough Sun 13 Sep 16:00 UTC · 15-year stretch",
    tier: "A",
    bands: ["today", "institutions", "stretch"],
    status: "live",
    pay: 4,
    security: 4,
    reputation: 5,
    balance: 4,
    fit: 4,
    rhyme: "Park-level AI capital. Attract the companies, then hold the cluster. Fifteen years on the JD is a stretch.",
    rhymeZh: "科学园这一层的 AI 资本。把公司吸引来，再守住集群。招聘启事上的十五年是拉伸。",
    stretch: true,
    portalOnly: true,
    desk: {
      apply: "HKSTP Apply Now. Phenom 1366190466. After A1 if the director seat is the want.",
      draft: "r4261511564452071214",
      caution: "Do not email hr@hkstp.org. Cantonese on JD — do not claim. Do not invent 15 AI/DS years. Cyberport Director of Strategic Business Planning is A36 after this if public-mission strategy is the want.",
    },
  },
  {
    id: "A36",
    rank: 11,
    title: "Director of Strategic Business Planning",
    titleZh: "战略业务规划总监",
    org: "Cyberport",
    location: "Hong Kong",
    href: "https://www.cyberport.hk/en/news/career_opportunities/",
    closeAt: "2026-09-30T23:59:00+08:00",
    closeNote: "Apply on or before 30 Sep 2026 · then until filled · official email to hr@cyberport.hk · 15-year stretch",
    tier: "A",
    bands: ["institutions", "stretch"],
    status: "live",
    pay: 4,
    security: 5,
    reputation: 4,
    balance: 4,
    fit: 3,
    rhyme: "Public-mission strategy next to the startup ecosystem. After HKSTP AI director. Fifteen years of planning is a stretch. Not a CVC cheque.",
    rhymeZh: "数码港的公共使命策略，贴着创业生态。科学园 AI 总监之后。十五年规划是拉伸。不是 CVC 支票。",
    stretch: true,
    desk: {
      apply: "Official email: Word CV + present/expected salary + available date to hr@cyberport.hk. Mark Ref# DOBSP260811W on the header. Draft first — send only after APPROVE.",
      draft: "r-8982494698727325487",
      caution:
        "Official JD: 15 years business strategy / planning / development, preferably management in a large organization; ecosystem building. English + Chinese on this JD — do not claim Cantonese. Fill [TO FILL] salary and date. Skip Director of AI Infrastructure DAI260819W (12–15 years GPU/HPC). Skip Head of Entrepreneurship HOE260811W (15 years incubation + Cantonese; Wilson Chan already Director of Entrepreneurship). Skip Head of Risk/Legal, SM Corp Comms, SM Funding 12-month, data-centre facility, Macro Fund AM, marketing AM.",
    },
  },
  {
    id: "A35",
    rank: 19,
    title: "Head, Cybersecurity and AI Governance",
    titleZh: "网络安全与人工智能治理主管",
    org: "Hong Kong Productivity Council",
    location: "Hong Kong",
    href: "https://careers.hkpc.org/job/Head%2C-Cybersecurity-and-AI-Governance/1366848966/",
    closeNote: "Phenom 1366848966 · Ref DTD/11055 · posted 3 Sep 2026 · apply in 2 weeks then until filled · 12–15-year cyber stretch",
    tier: "A",
    bands: ["institutions", "stretch"],
    status: "live",
    pay: 3,
    security: 5,
    reputation: 4,
    balance: 4,
    fit: 2,
    rhyme: "Statutory AI trust next to HKCERT. Flexi-work. Governance, not a live product or CVC seat. After HKSTP AI director only if public AI security is the want.",
    rhymeZh: "法定机构的 AI 信任，贴着香港电脑保安事故协调中心。弹性工时。治理，不是已上线产品或 CVC。只若公共 AI 安全是想要的，才在科学园 AI 总监之后。",
    stretch: true,
    portalOnly: true,
    desk: {
      apply: "HKPC e-Recruitment careers.hkpc.org Phenom 1366848966. Digital Trust and AI Transformation Division. Flexi-work hour on JD.",
      draft: "r7302180608840283025",
      caution:
        "12–15 years cybersecurity / digital risk / AI governance including 5 years leadership. Do not invent CISSP/CISM/ISO 42001. Not an AI-native builder desk. Skip HKPC Senior Consultant Cyber Security vs this Head seat. Skip FWD Director GenAI Digital Delivery R-0022016 (15-year SWE architecture) vs HSBC B4 / MS B34.",
    },
  },
  {
    id: "A31",
    rank: 15,
    title: "Chief Digital and Technology Officer",
    titleZh: "首席数字与技术官",
    org: "City University of Hong Kong",
    location: "Kowloon Tong, Hong Kong",
    href: "https://www.cityu.edu.hk/hro/en/job/current/administrative.asp?ref=uad-r30526",
    closeNote: "Ref R/305/26 · until filled · Rechecked NACAD Apply Now 9 Sep 21:00 UTC · HRO asp Incapsula from this desk",
    tier: "A",
    bands: ["institutions", "stretch"],
    status: "live",
    pay: 4,
    security: 5,
    reputation: 5,
    balance: 4,
    fit: 3,
    rhyme: "Alma mater. A CIO-class desk, not a CVC seat. The university already knows the name.",
    rhymeZh: "母校。CIO 级台面，不是 CVC 席。学校已经知道这个名字。",
    stretch: true,
    portalOnly: true,
    desk: {
      apply: "jobs1.cityu.edu.hk NACAD Apply Now button on Chief Digital and Technology Officer. Official JD uad-r30526. LinkedIn 4463824877 is a mirror.",
      draft: "r981486238148765924",
      caution:
        "Do not email hrojob@cityu.edu.hk. HRO administrative.asp is Incapsula from this desk. Skip CityU Post-Investment Manager — still absent from the 102-row NACAD dump 9 Sep 21:00 UTC. Skip HKU CIO & University Librarian 533668 vs this alumni CDTO. Skip CUHK EO II Project Manager (Technology Transfer) 2600017B / 2600011K — already closed July 2026.",
    },
  },
  {
    id: "A32",
    rank: 16,
    title: "Chief Director, AI Platform & Solutions",
    org: "ASTRI",
    location: "Hong Kong",
    href: "https://careers.astri.org/job/Chief-Director%2C-AI-Platform-%26-Solutions/53997644/",
    closeNote: "Official Apply live 10 Sep · until filled",
    tier: "A",
    bands: ["institutions", "stretch"],
    status: "live",
    pay: 4,
    security: 5,
    reputation: 4,
    balance: 3,
    fit: 3,
    rhyme: "Agentic platform for FinTech and the rest. After the ecosystem manager. Do not invent a PhD.",
    rhymeZh: "给金融科技和其他域用的智能体平台。生态经理之后。不要编博士。",
    stretch: true,
    portalOnly: true,
    desk: {
      apply: "ASTRI Apply Now 53997644. AFTER A22. Do not spray ASTRI engineering clones.",
      draft: "r253940768081559446",
      caution: "15+ years R&D leadership and PhD preferred — optional stretch only.",
    },
  },
  {
    id: "A22",
    rank: 11,
    title: "Senior Manager, Ecosystem and Channel",
    org: "ASTRI",
    location: "Hong Kong",
    href: "https://careers.astri.org/job/Deputy-Director%2C-Ecosystem-and-Channel/56190244/",
    tier: "A",
    bands: ["institutions"],
    status: "live",
    pay: 3,
    security: 5,
    reputation: 4,
    balance: 4,
    fit: 4,
    rhyme: "Applied-science ecosystem. Channel, not a lab coat. Title on the page is Senior Manager.",
    rhymeZh: "应用科学生态。渠道，不是实验袍。页面职称是高级经理。",
    portalOnly: true,
    desk: {
      apply: "ASTRI Apply Now Phenom 56190244. URL still says Deputy-Director. Official Apply live. Chief Director AI Platform is A32 after this.",
      draft: "r70476510155848527",
      caution: "Do not email a guessed ASTRI HR address. Do not email Manpower aston.yeung@manpowergrc.hk as this apply channel. Do not spray A32 (15-year / PhD stretch) with this SM seat.",
    },
  },
  {
    id: "A27",
    rank: 13,
    title: "Assistant Director, InnoHK and University Collaborations",
    org: "HKSTP",
    location: "Island East, Hong Kong",
    href: "https://careers.hkstp.org/job/Island-East-Assistant-Director%2C-InnoHK-and-University-Collaborations-HK-H/1366195766/",
    closeNote: "Official Apply live 10 Sep · 10-year startup ecosystem",
    tier: "A",
    bands: ["institutions", "cvc"],
    status: "live",
    pay: 4,
    security: 4,
    reputation: 4,
    balance: 4,
    fit: 4,
    rhyme: "InnoHK cluster plus university venture-building. After investor engagement. Then the Manager Uni Collab seat if this director-class desk is not the want.",
    rhymeZh: "InnoHK 集群，加上大学造企业。投资人对接之后。若这层主任席不是想要的，再经理席。",
    portalOnly: true,
    desk: {
      apply: "HKSTP Apply Now. Phenom 1366195766. After A1 then this. Then Manager University Collaborations 1366215966.",
      draft: "r-1603957299526558471",
      caution: "English + Putonghua. Do not claim Cantonese. Skip Senior Manager, New Ventures Programmes 1367071866 — JD is 10-year marketing/events, not ventures investing.",
    },
  },
  {
    id: "A27b",
    rank: 18,
    title: "Manager, University Collaborations",
    org: "HKSTP",
    location: "Island East, Hong Kong",
    href: "https://careers.hkstp.org/job/Island-East-Manager%2C-University-Collaborations-HK-H/1366215966/",
    closeNote: "Official Apply live 10 Sep · 8-year deeptech / incubation",
    tier: "A",
    bands: ["institutions", "cvc"],
    status: "live",
    pay: 3,
    security: 4,
    reputation: 4,
    balance: 5,
    fit: 4,
    rhyme: "Eight-year university venture-building. Five-day week. After the InnoHK assistant director if that desk is too high.",
    rhymeZh: "八年大学造企业。五天工作周。InnoHK 助理总监之后，若那层太高。",
    portalOnly: true,
    desk: {
      apply: "HKSTP Apply Now. Phenom 1366215966. AFTER A27. English + Putonghua. Do not claim Cantonese.",
      draft: "r-7994383117556414559",
    },
  },
  {
    id: "A34",
    rank: 11,
    title: "Senior Manager (Entrepreneurship and Funding), Knowledge Transfer Office",
    titleZh: "高级经理（创业与资助）",
    org: "Hong Kong Baptist University",
    location: "Kowloon Tong, Hong Kong",
    href: "https://fa-ewqq-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/job/25260765",
    closeNote: "Oracle 25260765 · until filled · posted 3 Jun 2026 · official ExternalPostedEndDate null rechecked 9 Sep 21:40 UTC · aggregator 1 Sep is stale"
    tier: "A",
    bands: ["institutions", "cvc", "stretch"],
    status: "live",
    pay: 3,
    security: 5,
    reputation: 4,
    balance: 5,
    fit: 4,
    rhyme: "University KTO next to investors and TSSSU. Ten years incubation is a stretch. After PolyU A4.",
    rhymeZh: "大学知识转移处，贴着投资人与 TSSSU。十年孵化是拉伸。先 PolyU A4。",
    stretch: true,
    portalOnly: true,
    desk: {
      apply: "HKBU e-Recruitment only. Oracle job 25260765. Review ongoing until filled. Written test for shortlist. 2-year fixed term.",
      draft: "r7973575122747931683",
      caution: "English + Chinese. Do not claim Cantonese. Do not email HRO. Do not invent 10 incubation years. Skip Creative Hub EO and Research Office grants seats vs this KTO desk. Aggregator deadline 1 Sep 2026 is stale — official Oracle ExternalPostedEndDate is null; re-GET 25260765 immediately before paste.",
    },
  },
  {
    id: "B4",
    rank: 5,
    title: "Senior AI Solution Lead",
    org: "HSBC",
    location: "Central, Hong Kong",
    href: "https://apply.careers.hsbc.com/job/Central-Senior-AI-Solution-Lead-Hong/1330173757/",
    closeAt: "2026-09-30T16:00:00Z",
    closeNote: "validThrough Wed 30 Sep",
    tier: "B",
    bands: ["capital"],
    status: "live",
    pay: 5,
    security: 5,
    reputation: 5,
    balance: 3,
    fit: 4,
    rhyme: "Bank AI that has to run. First HSBC gravity well — then digital platforms, then IWPB commercialization.",
    rhymeZh: "银行里必须能跑的 AI。汇丰第一口井 —— 再商业化，再货币。",
    portalOnly: true,
    desk: {
      apply: "HSBC Apply Now. Rechecked live 9 Sep 19:50 UTC. Prior isolation: validThrough Wed 30 Sep 16:00 UTC.",
      draft: "r-5150334973348395509",
      caution:
        "First HSBC gravity well. Then B159 (27 Sep) then B146 (19 Sep). Do not spray all HSBC seats the same week. Do not invent a numbered ML decade. Skip Head of HK AI Phenom 1369156757 — official: position filled. Skip Guangzhou Head of AI Software Development 1356439457 and Singapore HSBC Life Head of Data, AI & Intelligence 1369596457 vs this HK seat.",
    },
  },
  {
    id: "B159",
    rank: 14,
    title: "Business Capability and Solution Lead - Digital Platforms",
    org: "HSBC",
    location: "Kowloon City, Hong Kong",
    href: "https://apply.careers.hsbc.com/job/Kowloon-City-Business-Capability-and-Solution-Lead-Digital-Platforms-Kowl/1367725557/",
    closeAt: "2026-09-27T16:00:00Z",
    closeNote: "validThrough Sun 27 Sep 16:00 UTC · GCB 4",
    tier: "B",
    bands: ["capital", "stretch"],
    status: "live",
    pay: 4,
    security: 5,
    reputation: 5,
    balance: 3,
    fit: 3,
    rhyme: "AI-native and agentic banking on a digital-platform desk. After the AI solution lead. Eight-to-twelve-year consulting stretch.",
    rhymeZh: "数字平台上的原生 AI 与智能体银行。先 AI 方案负责人。八到十二年咨询拉伸。",
    stretch: true,
    desk: {
      apply: "HSBC Apply. After B4. GCB 4. 8–12 years management consulting / enterprise strategy / business architecture — do not invent.",
      draft: "r1038150271801325589",
      caution: "Skip Senior Strategic Planner 1367731657 (cost/FTE). Skip Sr AD 1370245557 (GPS architecture). Skip Treasury BM 1370434357. Skip Alts Business Architect 1369577157 vs B154. Sibling IWPB AI/ML commercialization is B146.",
    },
  },
  {
    id: "B146",
    rank: 15,
    title: "AI/ML Design Commercialization Manager, IWPB",
    org: "HSBC",
    location: "Central, Hong Kong",
    href: "https://apply.careers.hsbc.com/job/Central-AI-ML-Design-Commercialization-Manager-International-Wealth-and-Premier-Banking-Hong/1359802857/",
    closeAt: "2026-09-19T16:00:00Z",
    closeNote: "validThrough Sat 19 Sep · GCB 4 · 12-year stretch",
    tier: "B",
    bands: ["capital", "stretch"],
    status: "live",
    pay: 4,
    security: 5,
    reputation: 5,
    balance: 3,
    fit: 3,
    rhyme: "Wealth AI commercialization. After the solution lead. Hands-on analytics bar is a stretch.",
    rhymeZh: "财富 AI 商业化。方案负责人之后。动手分析门槛是拉伸。",
    stretch: true,
    desk: {
      apply: "HSBC Apply 1359802857. After B4. GCB 4. Rechecked live validThrough Sat 19 Sep 16:00 UTC.",
      draft: "r-2204173744577221507",
      addendum: "Earlier pack r-4207723545408746455.",
      caution: "Minimum 12 years hands-on analytics — do not invent. Same close clock as B146's week-end with B138 Fri 18 Sep. Do not spray B144 (closes Sat 12) unless CE-office growth is also the want.",
    },
  },
  {
    id: "B154",
    rank: 14,
    title: "Head of Alts Investment Solutions, Data and Automation",
    org: "HSBC Global Asset Management",
    location: "Central, Hong Kong",
    href: "https://apply.careers.hsbc.com/job/Central-Head-of-Alts-Investment-Solutions%2C-Data-and-Automation-HSBC-Global-Asset-Management-Hong/1369577357/",
    closeAt: "2026-09-30T16:00:00Z",
    closeNote: "validThrough Wed 30 Sep 16:00 UTC · GCB 4",
    tier: "B",
    bands: ["capital", "stretch"],
    status: "live",
    pay: 5,
    security: 5,
    reputation: 5,
    balance: 3,
    fit: 4,
    rhyme: "Asset-management operations with a data-and-AI mandate. After the AI solution lead. Named alts platforms are a stretch — do not invent eFront.",
    rhymeZh: "资管运营，带着数据与 AI 的任务。先 AI 方案负责人。点名的另类平台是拉伸 —— 不要编造 eFront。",
    stretch: true,
    desk: {
      apply: "HSBC Apply Now. Phenom 1369577357. After B4. Skip Director, Investment Strategy 1371461457 — House View economist, not this ops/AI seat.",
      draft: "r3331028330889342623",
    },
  },
  {
    id: "B157",
    rank: 22,
    title: "Head of Alts Ops Valuation Oversight",
    org: "HSBC Global Asset Management",
    location: "Central, Hong Kong",
    href: "https://apply.careers.hsbc.com/job/Central-Head-of-Alts-Ops-Valuation-Oversight-HSBC-Global-Asset-Management-Hong/1367968757/",
    closeAt: "2026-09-14T16:00:00Z",
    closeNote: "validThrough Mon 14 Sep 16:00 UTC · GCB 4",
    tier: "B",
    bands: ["today", "capital", "stretch"],
    status: "live",
    pay: 5,
    security: 5,
    reputation: 5,
    balance: 3,
    fit: 3,
    rhyme: "AM ops that has to hold independence. AI is on the JD as tooling, not the product. After B154. Closes 14 Sep UTC.",
    rhymeZh: "资管运营，要守住独立性。AI 在招聘启事上是工具，不是产品。B154 之后。14 Sep UTC 截止。",
    stretch: true,
    desk: {
      apply: "HSBC Apply Now. Phenom 1367968757. After B4 then B154 then this if valuation oversight is the want.",
      draft: "r-7019214125721853508",
      caution: "Do not invent CFA/CAIA or valuation-specialist years. Skip HKEX SVP IT Project Management R004449 vs AI-native.",
    },
  },
  {
    id: "B158",
    rank: 21,
    title: "AVP, Channel Management & Experience, Digital",
    org: "DBS",
    location: "One Island East, Hong Kong",
    href: "https://dbs.wd3.myworkdayjobs.com/DBS_Careers/job/One-Island-East/Assistant-Vice-President--Channel-Management---Experience--Digital_WD85621",
    closeNote: "Workday WD85621 · posted 5 days ago · 6–8 year digital banking",
    tier: "B",
    bands: ["capital"],
    status: "live",
    pay: 4,
    security: 5,
    reputation: 4,
    balance: 3,
    fit: 4,
    rhyme: "Bank digital channels with AI on the roadmap. After HSBC B4. AVP, not a director seat.",
    rhymeZh: "银行数字渠道，路线图上有 AI。先汇丰 B4。副总裁，不是总监席。",
    desk: {
      apply: "dbs.wd3 DBS_Careers WD85621. One Island East. After B4 if the digital-channel seat is the want.",
      draft: "r-6768283435307523797",
    },
  },
  {
    id: "B138",
    rank: 16,
    title: "Senior Product Manager, Markets & Securities Services",
    org: "HSBC",
    location: "Hong Kong",
    href: "https://apply.careers.hsbc.com/job/Central-Senior-Product-Manager-Markets-Securities-Services-Hong/1367848757/",
    closeAt: "2026-09-18T16:00:00Z",
    closeNote: "validThrough Fri 18 Sep · digital-asset custody",
    tier: "B",
    bands: ["capital"],
    status: "live",
    pay: 4,
    security: 5,
    reputation: 5,
    balance: 3,
    fit: 4,
    rhyme: "Custody product. Digital assets with a bank spine.",
    rhymeZh: "托管产品。数字资产，银行脊骨。",
    desk: { apply: "After B4 → B121 → B76 then this.", draft: "r-6811361595115717280" },
  },
  {
    id: "B6",
    rank: 4,
    title: "SVP, AI Adoption and Commercialization",
    org: "Citi",
    location: "Hong Kong",
    href: "https://jobs.citi.com/job/hong-kong/senior-vice-president-ai-adoption-and-commercialization-senior-lead/287/99751202496",
    closeNote: "Job Req 26990009 · posted 26 Aug 2026",
    tier: "B",
    bands: ["capital"],
    status: "live",
    pay: 5,
    security: 5,
    reputation: 5,
    balance: 3,
    fit: 4,
    rhyme: "Adoption that has to sell inside a bank. Commercialization, not a lab.",
    rhymeZh: "银行内部必须卖得出去的采用。商业化，不是实验室。",
    desk: {
      apply: "Citi portal. Cover r-962642582042496067 + addendum r8039054950086008481.",
      draft: "r-962642582042496067",
    },
  },
  {
    id: "B34",
    rank: 3,
    title: "Applied AI Lead, Executive Director",
    org: "Morgan Stanley",
    location: "Hong Kong",
    href: "https://ms.wd5.myworkdayjobs.com/External/job/Hong-Kong-Hong-Kong/Applied-AI-Lead--Executive-Director--Enterprise-Technology-Services_PT-JR037195",
    tier: "B",
    bands: ["capital"],
    status: "live",
    pay: 5,
    security: 5,
    reputation: 5,
    balance: 3,
    fit: 4,
    rhyme: "Applied AI at a markets house. Reputation ceiling, bank hours. Twelve-year / five-year VP stretch — do not invent ETS years.",
    rhymeZh: "市场机构里的应用 AI。名声天花板，银行工时。十二年 / 五年 VP 拉伸 —— 不要编造 ETS 年资。",
    stretch: true,
    desk: {
      apply: "Official Workday External PT-JR037195. canApply true. Hong Kong. Posted 30+ days.",
      draft: "r2694556748870183470",
      addendum: "r3980890194948961269",
      caution: "12+ years FS tech strategy/PMO/TPM and 5 years VP+ at a global FI. Technical roots in SWE/data/applied AI. Do not invent those years. Skip Applied AI Engineer VP IST PT-JR043455 vs this ED lead — do not spray both.",
    },
  },
  {
    id: "B72",
    rank: 2,
    title: "M&A SA / AD, Portfolio Management, SEA & India",
    org: "Tencent",
    location: "Hong Kong / SEA",
    href: "https://careers.tencent.com/",
    closeNote: "postId 2089180506259374080",
    tier: "cvc",
    bands: ["cvc", "capital"],
    status: "live",
    pay: 5,
    security: 3,
    reputation: 5,
    balance: 3,
    fit: 4,
    rhyme: "Platform CVC. Portfolio as a craft. China-background capital with a Hong Kong desk.",
    rhymeZh: "平台 CVC。组合是手艺。中资背景，香港台面。",
    desk: { apply: "Tencent career postId 2089180506259374080.", draft: "r-2146671588397327289" },
  },
  {
    id: "B163",
    rank: 16,
    title: "AVP, Health Innovation & Venture Scouting Lead",
    org: "FWD Group",
    location: "Taikoo Shing (Group Office), Hong Kong",
    href: "https://fwd.wd3.myworkdayjobs.com/FWDcareersite/job/Hong-Kong---Taikoo-Shing-Group-Office/Assistant-Vice-President--Health-Innovation---Venture-Scouting-Lead_JR-0027501",
    closeNote: "Workday FWDcareersite JR-0027501 · canApply true · posted 30+ days · no endDate",
    tier: "B",
    bands: ["cvc", "capital", "stretch"],
    status: "live",
    pay: 4,
    security: 3,
    reputation: 4,
    balance: 3,
    fit: 4,
    rhyme: "Listed-insurer venture scouting next to AI-enabled health. Angel-adjacent. Health-tech years are a stretch. After Meitu if the scouting desk is the want.",
    rhymeZh: "上市保险公司的风投扫描，贴着带 AI 的健康。贴近天使。健康科技年资是拉伸。美图之后，若扫描席是想要的。",
    stretch: true,
    portalOnly: true,
    desk: {
      apply: "Official Workday fwd.wd3 FWDcareersite JR-0027501. Hong Kong - Taikoo Shing (Group Office). canApply true.",
      draft: "r-5576916900423828272",
      caution:
        "Minimum 8 years health technology / insurtech / digital health / innovation or venture partnerships — do not invent a health-tech decade. LinkedIn 4451617224 is a mirror. Sibling Group Digital Platforms is B164 — do not spray both. Skip Director, GenAI Digital Delivery R-0022016 (15+ years SWE/architecture, CS degree) vs B4/B34. Skip Head of Investment Management JR-0027167 (15-year insurance AM / CFA). Skip OCBC VP Head of Digital Wealth & Payments until an official careers URL exists (LinkedIn-only 4460947342). Skip RGA Executive Director Digital Product Solutions J27314 — official careers: no longer posted.",
    },
  },
  {
    id: "B164",
    rank: 18,
    title: "Director, Group Digital Platforms",
    org: "FWD Group",
    location: "Taikoo Shing (Group Office), Hong Kong",
    href: "https://fwd.wd3.myworkdayjobs.com/FWDcareersite/job/Hong-Kong---Taikoo-Shing-Group-Office/Director--Product-Management_JR-0023912",
    closeNote: "Workday FWDcareersite JR-0023912 · canApply true · posted 30+ days · slug Director--Product-Management",
    tier: "B",
    bands: ["capital", "stretch"],
    status: "live",
    pay: 4,
    security: 3,
    reputation: 4,
    balance: 3,
    fit: 3,
    rhyme: "Regional digital product platform for distribution. After venture scouting. Ten-year insurtech and seven-year mobile are stretches.",
    rhymeZh: "区域数字产品平台，给分销用。先风投扫描。十年保险科技与七年移动是拉伸。",
    stretch: true,
    portalOnly: true,
    desk: {
      apply: "Official Workday JR-0023912. Title Director, Group Digital Platforms. Path Director--Product-Management. AFTER B163. Do not spray both FWD seats.",
      draft: "r4900752038167597996",
      caution:
        "10+ years e-commerce/InsurTech-Fintech and 7+ years mobile + Agile product. Do not invent those years. Skip Head of Investment Management JR-0027167 vs this product seat.",
    },
  },
  {
    id: "B36",
    rank: 17,
    title: "Senior Director / Director, AI & Data Strategy",
    org: "Manulife",
    location: "Hong Kong",
    href: "https://manulife.wd3.myworkdayjobs.com/MFCJH_Jobs/job/Hong-Kong/Senior-Director---Director-AI---Data-Strategy---Transformation-Lead_JR26071432",
    closeAt: "2026-09-30T23:59:00+08:00",
    closeNote: "Workday close 30 Sep 2026",
    tier: "B",
    bands: ["capital"],
    status: "live",
    pay: 4,
    security: 4,
    reputation: 4,
    balance: 3,
    fit: 4,
    rhyme: "Asia AI strategy in a life-company. Then digitization (B100), then optional manager (B35).",
    rhymeZh: "寿险公司的亚洲 AI 策略。然后数字化（B100），再可选经理（B35）。",
    desk: {
      apply: "Tenant manulife.wd3.myworkdayjobs.com/MFCJH_Jobs. Cover r5801903241139313616. Rechecked canApply true, endDate 2026-09-30.",
      draft: "r5801903241139313616",
      addendum: "r4654668089183427838",
      caution: "Then B100 digitization. Optional B35 AI Adoption Manager. Do not spray all three.",
    },
  },
  {
    id: "B100",
    rank: 18,
    title: "Director, Digitization & Automation, GWAM & GA Asia Operations",
    org: "Manulife",
    location: "Hong Kong",
    href: "https://manulife.wd3.myworkdayjobs.com/MFCJH_Jobs/job/Hong-Kong/Director--Digitization---Automation--GWAM---GA-Asia-Operations_JR26031019-1",
    closeAt: "2026-12-31T23:59:00+08:00",
    closeNote: "Workday canApply true · endDate 31 Dec 2026 · AFTER B36",
    tier: "B",
    bands: ["capital"],
    status: "live",
    pay: 4,
    security: 4,
    reputation: 4,
    balance: 3,
    fit: 4,
    rhyme: "Asset-management operations with automation and AI. After the Asia AI strategy director. Microsoft stack on the JD is a tool, not a claim.",
    rhymeZh: "资管运营，带着自动化与 AI。先亚洲 AI 策略总监。招聘启事上的微软栈是工具，不要当成声称。",
    portalOnly: true,
    desk: {
      apply: "Workday MFCJH_Jobs JR26031019-1. Hong Kong. AFTER B36. Do not spray B35.",
      draft: "r-2420965189264840193",
      caution: "No Cantonese on JD. Do not invent Power Platform years. Skip Manager/SM AI JR26070767 vs B36. Skip Senior AI Developer / ML Engineer vs this director seat.",
    },
  },
  {
    id: "B35",
    rank: 28,
    title: "AI Adoption Manager, Asia",
    org: "Manulife",
    location: "Hong Kong",
    href: "https://manulife.wd3.myworkdayjobs.com/MFCJH_Jobs/job/Hong-Kong/AI-Adoption-Manager--Asia_JR26060321-1",
    closeAt: "2026-09-30T23:59:00+08:00",
    closeNote: "Workday canApply true · endDate 30 Sep 2026 · manager step-down after B36",
    tier: "B",
    bands: ["capital"],
    status: "live",
    pay: 3,
    security: 4,
    reputation: 4,
    balance: 3,
    fit: 3,
    rhyme: "Copilot enablement for Asia staff. After the director seats only if a manager path is the want.",
    rhymeZh: "亚洲员工的 Copilot 采用。只若要经理路径，才在总监席之后。",
    desk: {
      apply: "Workday JR26060321-1. AFTER B36 then B100. Do not spray with the director seats.",
      draft: "r-2416333065168456684",
      caution: "5+ years change management. Reports to AI Change Enablement Lead. Not a high-pay director desk.",
    },
  },
  {
    id: "B19",
    rank: 19,
    title: "Product Owner — Multi-Asset",
    org: "Fidelity",
    location: "Hong Kong",
    href: "https://fil.wd3.myworkdayjobs.com/001/job/Hong-Kong-Office-New/Product-Owner---Multi-Asset_J69405",
    closeAt: "2026-09-30T23:59:00+08:00",
    closeNote: "Close 30 Sep 2026 · path Hong-Kong-Office-New",
    tier: "B",
    bands: ["capital"],
    status: "live",
    pay: 4,
    security: 4,
    reputation: 5,
    balance: 3,
    fit: 4,
    rhyme: "Multi-asset product owner. Fund craft, not a chatbot seat.",
    rhymeZh: "多元资产产品负责人。基金手艺，不是聊天机器人席。",
    desk: {
      apply: "Workday J69405. Pack r7257447307743357641. Rechecked live validThrough 2026-09-30.",
      draft: "r7257447307743357641",
      addendum: "r4621871729198491241",
      caution: "Sibling Product Owner - Fixed Income J70844 is B160. Do not spray both.",
    },
  },
  {
    id: "B160",
    rank: 21,
    title: "Product Owner - Fixed Income",
    org: "Fidelity",
    location: "Hong Kong",
    href: "https://fil.wd3.myworkdayjobs.com/001/job/Hong-Kong-Office-New/Product-Owner---Fixed-Income_J70844",
    closeAt: "2026-10-31T23:59:00+08:00",
    closeNote: "validThrough 31 Oct 2026 · after B19 · do not spray both",
    tier: "B",
    bands: ["capital"],
    status: "live",
    pay: 4,
    security: 4,
    reputation: 5,
    balance: 3,
    fit: 3,
    rhyme: "AM-platform product owner for fixed income. After multi-asset. Fund craft, not AI-native building. London Equity J70839 is a different seat — skip it.",
    rhymeZh: "固收平台产品负责人。先多元资产。基金手艺，不是原生 AI 建造。伦敦股权席不要投。",
    desk: {
      apply: "Workday 001 J70844. Hong-Kong-Office-New. After B19 only if the FI platform seat is the one you want.",
      draft: "r7682432615610235067",
      caution: "Do not spray J69405 and J70844. Skip London Equity J70839 (Cannon Street, close 25 Sep).",
    },
  },
  {
    id: "B166",
    rank: 23,
    title: "Lead Product Owner",
    org: "The Hong Kong Jockey Club",
    location: "Sha Tin, Hong Kong",
    href: "https://careers.hkjc.com/job/Sha-Tin-Lead-Product-Owner-New/1363803666/",
    closeNote: "Phenom 1363803666 · Req 4956 · posted 30 Aug 2026 · no validThrough · portal Apply Now",
    tier: "B",
    bands: ["capital"],
    status: "live",
    pay: 4,
    security: 5,
    reputation: 5,
    balance: 4,
    fit: 3,
    rhyme: "Regulated product ownership at a Hong Kong institution. Wagering preferred. After bank product seats if the Club desk is the want. Not AI-native building.",
    rhymeZh: "马会的受规管产品负责人。博彩优先。银行产品席之后，若马会台面是想要的。不是原生 AI 建造。",
    portalOnly: true,
    desk: {
      apply: "HKJC careers.hkjc.com Apply Now. Phenom 1363803666. Do not email careers@hkjc.org.hk except accommodations.",
      draft: "r1675551980814589962",
      caution:
        "Official JD: 10 years product delivery / system behaviour / software execution; 5 years people management; regulated/high-risk (wagering, finance, fintech, payments). Wagering preferred — do not invent racing years. Skip sibling Product Owner 1364823466 (6 years). Skip Deputy Executive Manager Digital Experience 1358812866 (PMO/governance, not product/CVC). Skip CSOP AI Agent Developer until an official csopasset.com experienced-professional URL exists (IC builder, too junior vs director path). Skip BEA Section Head Digital & Channel Management LinkedIn 4426049341 — no longer accepting. Skip HKUST Head (Administration) OKT — closed Jun/Jul 2026. Skip CUHK KTO Director — Kelvin Wong in seat since Jul 2026.",
    },
  },
  {
    id: "B50",
    rank: 20,
    title: "Senior Manager, APAC Product Owner — Digital Distribution",
    org: "Invesco",
    location: "Hong Kong",
    href: "https://invesco.wd1.myworkdayjobs.com/en-US/IVZ/job/Hong-Kong-Hong-Kong/Senior-Manager--APAC-Product-Owner---Digital-Distribution---Enterprise-Engineering_R-14368",
    tier: "B",
    bands: ["capital"],
    status: "live",
    pay: 4,
    security: 4,
    reputation: 4,
    balance: 3,
    fit: 4,
    rhyme: "Asset-manager digital distribution. After Fidelity, if the product-owner craft is the want.",
    rhymeZh: "资管数字分销。富达之后，若产品负责人手艺是想要的。",
    desk: { apply: "Invesco Workday R-14368." },
  },
  {
    id: "B153",
    rank: 20,
    title: "Associate Director, Distribution Digital",
    org: "AIA",
    location: "Hong Kong, AIA Group Office",
    href: "https://aia.wd3.myworkdayjobs.com/en-US/External/job/Hong-Kong-HK-AIA-Group-Office/Associate-Director--Digital-Agency-Platforms_JR-68436-1",
    closeAt: "2026-09-30T23:59:00+08:00",
    closeNote: "CXS canApply true · endDate 2026-09-30 · slug JR-68436-1",
    tier: "B",
    bands: ["capital", "stretch"],
    status: "live",
    pay: 4,
    security: 4,
    reputation: 4,
    balance: 3,
    fit: 3,
    rhyme: "Agency platforms with AI inside. Group Office, not Macau path. Twelve to fifteen years is a stretch. Then Customer AI.",
    rhymeZh: "代理平台，里面有 AI。集团办公室，不是澳门那条路径。十二到十五年是拉伸。然后才是客户 AI。",
    stretch: true,
    portalOnly: true,
    desk: {
      apply: "Workday External JR-68436-1. Path Hong-Kong-HK-AIA-Group-Office. AFTER B9b, before B117.",
      draft: "r-1064563125725395723",
      caution: "Do not use JR-68436 without -1. Skip JR-69111 Digital Engineering. Skip JR-68841 People Digital (Digital HR). Skip JR-67573-1 Data Analytics and AI (DS delivery). Skip JR-68248 Agency Digital Principal (Cantonese). Skip JR-69776-1 Customer Digital BD (wellness, Cantonese).",
    },
  },
  {
    id: "B117",
    rank: 21,
    title: "Associate Director, Customer AI & Analytics Product Management",
    org: "AIA",
    location: "Hong Kong / Macau",
    href: "https://aia.wd3.myworkdayjobs.com/en-US/External/job/Hong-Kong-HK-AIA-Hong-Kong--Macau/Associate-Director--Customer-AI---Analytics-Product-Management_JR-68056",
    tier: "B",
    bands: ["capital"],
    status: "live",
    pay: 4,
    security: 4,
    reputation: 4,
    balance: 3,
    fit: 4,
    rhyme: "Customer AI product. After Distribution Digital B153. Skip the engineering-strategy clone.",
    rhymeZh: "客户 AI 产品。分销数字之后。跳过工程策略那条克隆。",
    desk: {
      apply: "AIA Workday JR-68056. Path Hong-Kong-HK-AIA-Hong-Kong--Macau.",
      addendum: "r-1766768802526645146",
    },
  },
  {
    id: "B33",
    rank: 22,
    title: "Product Owner, AI in Brand & Marketing",
    org: "Zurich",
    location: "Hong Kong / Singapore / Malaysia",
    href: "https://www.careers.zurich.com/job/Hong-Kong-Product-Owner%2C-AI-in-Brand-%26-Marketing/1368805957/",
    tier: "B",
    bands: ["capital"],
    status: "live",
    pay: 3,
    security: 4,
    reputation: 4,
    balance: 3,
    fit: 4,
    rhyme: "Agentic marketing product. Confirm the Hong Kong seat. Phenom, not Workday.",
    rhymeZh: "代理式营销产品。确认香港席。Phenom，不是 Workday。",
    confirmSeat: true,
    desk: {
      apply: "www.careers.zurich.com Phenom 1368805957. Do not use zurich.wd3.",
      draft: "r-8168033812393573138",
      caution: "CONFIRM HK SEAT. Possible step-down vs Director.",
    },
  },
  {
    id: "B73",
    rank: 23,
    title: "Principal / Senior PM, AI and Agent",
    org: "OKX",
    location: "Hong Kong",
    href: "https://job-boards.greenhouse.io/okx/jobs/7531920003",
    tier: "cvc",
    bands: ["cvc", "capital"],
    status: "live",
    pay: 5,
    security: 2,
    reputation: 3,
    balance: 2,
    fit: 4,
    rhyme: "Agentic product at an exchange. High cash, thinner security and hours. HK right-to-work first.",
    rhymeZh: "交易所的代理产品。现金高，安全与工时更薄。香港工作权优先。",
    desk: {
      apply: "Greenhouse 7531920003. Then optional B174 VP AI Strategy or B177 VP Product AI & Agent — pick one. Wallet AI is B152. Do not spray PM clones. Skip Singapore VP clone 7684887003. Skip AI Agent Product Expert (Middleware) 7731745003 vs this PM seat.",
    },
  },
  {
    id: "B174",
    rank: 24,
    title: "Vice President, AI Strategy & Transformation",
    titleZh: "人工智能策略与转型副总裁",
    org: "OKX",
    location: "Hong Kong",
    href: "https://job-boards.greenhouse.io/okx/jobs/7684888003",
    closeNote: "Greenhouse 7684888003 · official HK Apply live 9 Sep 20:15 UTC · sibling 7684887003 is Singapore",
    tier: "cvc",
    bands: ["cvc", "capital", "stretch"],
    status: "live",
    pay: 5,
    security: 2,
    reputation: 3,
    balance: 2,
    fit: 4,
    rhyme: "Company AI roadmap next to live products. After the agent PM if this is the strategy seat. Ten AI years and a doctorate are stretches.",
    rhymeZh: "公司这一层的 AI 路线，贴着已上线产品。先代理产品经理，若这才是策略席。十年 AI 与博士都是拉伸。",
    stretch: true,
    portalOnly: true,
    desk: {
      apply: "Official Greenhouse 7684888003 Hong Kong. After B73. Do not spray with B177 VP Product or B152 the same week.",
      draft: "r-1746679636804214893",
      caution:
        "10+ years AI/deep learning, 5 years Director+, MS/PhD, publication/open-source on JD — do not invent. Skip Singapore clone 7684887003. Sibling VP Product is B177 7691999003. HK right-to-work first.",
    },
  },
  {
    id: "B177",
    rank: 24,
    title: "Vice President of Product, AI and Agent",
    titleZh: "产品副总裁 · AI 与智能体",
    org: "OKX",
    location: "Hong Kong",
    href: "https://job-boards.greenhouse.io/okx/jobs/7691999003",
    closeNote: "Greenhouse 7691999003 · official HK Apply live 9 Sep 20:05 UTC · sibling 7691998003 is Singapore",
    tier: "cvc",
    bands: ["cvc", "capital", "stretch"],
    status: "live",
    pay: 5,
    security: 2,
    reputation: 3,
    balance: 2,
    fit: 4,
    rhyme: "The product VP of the agent. After the PM if this is the seat that owns the assistant. Twelve years is a stretch.",
    rhymeZh: "智能体这一层的产品副总裁。先产品经理，若这才是要守的助手。十二年是拉伸。",
    stretch: true,
    portalOnly: true,
    desk: {
      apply: "Official Greenhouse 7691999003 Hong Kong. After B73. Pick this OR B174, not both the same week.",
      draft: "r-449291215686061085",
      caution:
        "12+ years product & tech, 5+ years senior leadership owning complex products, conversational/agentic AI as owner not contributor. English and Mandarin on JD — do not claim Cantonese. Skip Singapore clone 7691998003. Trading asked on the form — honest about the hedge book since Sep 2025.",
    },
  },
  {
    id: "B152",
    rank: 23,
    title: "Principal / Senior PM, AI & Web3 Wallet",
    org: "OKX",
    location: "Hong Kong",
    href: "https://job-boards.greenhouse.io/okx/jobs/7777029003",
    closeNote: "Greenhouse live 10 Sep 2026",
    tier: "cvc",
    bands: ["cvc", "capital"],
    status: "live",
    pay: 5,
    security: 2,
    reputation: 3,
    balance: 2,
    fit: 4,
    rhyme: "Wallet plus agent. After the AI-and-Agent PM, if that is the product you want to hold.",
    rhymeZh: "钱包加上代理。先 AI and Agent 产品经理，若这才是要守的产品。",
    desk: {
      apply: "Greenhouse 7777029003. AFTER B73. Confirm HK seat. Do not spray OKX PM clones.",
      draft: "r-8203520062962774517",
    },
  },
  {
    id: "B149",
    rank: 23,
    title: "Senior Product Manager, Agentic Enablement (Platform AI)",
    org: "Reap",
    location: "Quarry Bay, Hong Kong",
    href: "https://careers.reap.global/jobs/8342685-senior-product-manager-agentic-enablement-platform-ai",
    closeNote: "LinkedIn 4464641446 · posted ~22h ago · official Apply 9 Sep",
    tier: "cvc",
    bands: ["cvc", "capital"],
    status: "live",
    pay: 4,
    security: 2,
    reputation: 3,
    balance: 2,
    fit: 4,
    rhyme: "Hong Kong-headquartered fintech standing up agentic rails. High AI-native fit. Below the bank/university bar for hours and security.",
    rhymeZh: "香港总部的金融科技，在搭代理式轨道。AI 原生贴合高。工时与安全低于银行/大学那条杠。",
    desk: {
      apply: "careers.reap.global 8342685. After OKX B73 if the HK-HQ agentic platform is the want. Skip Reap Engineering Manager AI Agentic vs this PM seat.",
      draft: "r-7528244399176004260",
    },
  },
  {
    id: "B155",
    rank: 26,
    title: "Product Manager",
    org: "HashKey Capital",
    location: "Hong Kong",
    href: "https://hashkey.capital/careers/details44_611.html",
    closeNote: "Official getJobList id 611 · Apply Now to sgrecruitment@hashkey.com",
    tier: "cvc",
    bands: ["cvc", "capital"],
    status: "live",
    pay: 3,
    security: 2,
    reputation: 3,
    balance: 2,
    fit: 4,
    rhyme: "TradFi-and-Web3 fund product. SFC product lifecycle plus AI tools on the JD. PM, not the LinkedIn Product Director.",
    rhymeZh: "传统金融与 Web3 基金产品。持牌产品生命周期，招聘启事上还有 AI 工具。产品经理，不是 LinkedIn 上的产品总监。",
    desk: {
      apply: "Official JD Apply Now: sgrecruitment@hashkey.com. details44_611.html. After bank/university. Do not also spray Product Manager/Specialist 593.",
      draft: "r2852953938224944669",
      caution:
        "LinkedIn Product Director 4463321930 is not on official getJobList (ids 694, 692, 613, 612, 611, 593, 454, 445). Do not apply via LinkedIn-only. Skip Risk Director 612 vs AI-native builder. Skip BD Manager 454 vs this product seat.",
    },
  },
  {
    id: "B156",
    rank: 31,
    title: "Director, Technology Investment",
    org: "CLSA Capital Partners",
    location: "Hong Kong (Singapore listed as additional)",
    href: "https://citicclsa.wd3.myworkdayjobs.com/External/job/Hong-Kong/Director--Technology-Investment--CLSA-Capital-Partners_JR001362-1",
    closeNote: "Workday JR001362 · posted 30+ days · HK required · 15-year PE stretch",
    tier: "cvc",
    bands: ["cvc", "stretch"],
    status: "live",
    pay: 5,
    security: 3,
    reputation: 4,
    balance: 2,
    fit: 2,
    rhyme: "Official PE seat at last. Fifteen years and ten in USD growth funds is not the edge. After Meitu, only if classic PE is the want.",
    rhymeZh: "终于有官网 PE 席。十五年、十年美元成长基金，不是这条长处。美图之后，只若要的是经典 PE。",
    stretch: true,
    portalOnly: true,
    desk: {
      apply: "citicclsa.wd3 External JR001362-1. Hiring org: CITIC CLSA Capital Partners HK Limited. English + Mandarin. Experienced candidate considered as ED.",
      draft: "r-8224629745074945869",
      caution:
        "Do not invent 15 PE years or a Master’s. Cantonese is a bonus — do not claim. LinkedIn 4278483732 says no longer accepting; official Workday canApply still true 9 Sep 19:55 UTC. Do not apply LinkedIn-only.",
    },
  },
  {
    id: "B150",
    rank: 24,
    title: "Senior Product Manager — TradFi Wealth",
    org: "Binance",
    location: "Hong Kong / Remote",
    href: "https://jobs.lever.co/binance/1c3e9e01-82b8-4840-85b1-82cabd86bcfd",
    closeNote: "Lever Apply 9 Sep · confirm Hong Kong seat vs Remote",
    tier: "cvc",
    bands: ["cvc", "capital"],
    status: "live",
    pay: 5,
    security: 2,
    reputation: 3,
    balance: 2,
    fit: 4,
    rhyme: "TradFi wealth product on an exchange. Trading and asset-management habits meet a live product seat. Confirm Hong Kong. Do not spray Binance PM clones.",
    rhymeZh: "交易所上的传统金融财富产品。交易与资管习惯碰上产品席。确认香港。不要群发币安产品克隆。",
    confirmSeat: true,
    desk: {
      apply: "jobs.lever.co/binance/1c3e9e01-82b8-4840-85b1-82cabd86bcfd. Then optional AI Agent & Harness B151. Skip Stock Trading AM vs this wealth seat. Skip accelerator/junior. Skip Product Manager - AI growth bc1302e3 (5-year growth/fission PM, Remote Asia/HK/Taiwan) vs this wealth seat.",
      draft: "r2859635877950117754",
    },
  },
  {
    id: "B151",
    rank: 25,
    title: "Product Manager, AI Agent & Harness",
    org: "Binance",
    location: "Hong Kong / Remote",
    href: "https://jobs.lever.co/binance/0a03c5e3-4a06-4aa7-8c06-25a473ceeb33",
    closeNote: "Lever Apply 9 Sep · after B150 only",
    tier: "cvc",
    bands: ["cvc"],
    status: "live",
    pay: 4,
    security: 2,
    reputation: 3,
    balance: 2,
    fit: 4,
    rhyme: "Agent harness product. After TradFi wealth, only if the agent seat is the one you want. Do not also spray chatbot / search PM clones.",
    rhymeZh: "代理挽具产品。传统金融财富之后，只若这个代理席是想要的。不要再群发聊天机器人/搜索克隆。",
    desk: {
      apply: "jobs.lever.co/binance/0a03c5e3-4a06-4aa7-8c06-25a473ceeb33. AFTER B150. Skip AI Chatbot PM and AI Search contract.",
      draft: "r-8111998692901901578",
    },
  },
  {
    id: "B113",
    rank: 27,
    title: "Product Lead – AI Investing",
    org: "BJAK",
    location: "Hong Kong",
    href: "https://jobs.ashbyhq.com/bjakcareer/c3e6469e-684d-4ecd-843a-ce3f7da8cf4d",
    tier: "cvc",
    bands: ["cvc", "stretch"],
    status: "live",
    pay: 4,
    security: 2,
    reputation: 2,
    balance: 1,
    fit: 4,
    rhyme: "AI investing product. Below the bank/university bar for hours. One vertical only — do not spray clones.",
    rhymeZh: "AI 投资产品。工时低于银行/大学那条杠。只选一条垂类 —— 不要群发克隆。",
    stretch: true,
    desk: {
      apply: "Ashby. Then optional TPM stockbroking, then Head of Strategy. Pick one vertical.",
      caution: "JD says not counting hours.",
    },
  },
  {
    id: "B110",
    rank: 24,
    title: "Innovation Manager – Product Management",
    org: "BOCHK",
    location: "Hong Kong",
    href: "https://careers.pageuppeople.com/798/cw/en/job/500073",
    tier: "B",
    bands: ["capital"],
    status: "live",
    pay: 4,
    security: 5,
    reputation: 4,
    balance: 3,
    fit: 4,
    rhyme: "Bank innovation with a product-management name. Skip the 4-year digital-strategy manager beside it.",
    rhymeZh: "银行创新，名字叫产品管理。旁边那条四年数字策略经理不要投。",
    desk: {
      apply: "PageUp 500073 still Apply 9 Sep.",
      caution: "Skip Digital Strategy and Transformation Manager 500080 — official JD is 4 years, close 30 Nov 2026, Putonghua. Too junior vs this innovation seat.",
    },
  },
  {
    id: "B40b",
    rank: 25,
    title: "AVP, ETP Product",
    org: "HKEX",
    location: "Hong Kong",
    href: "https://hkex.wd3.myworkdayjobs.com/HKEXCareerPage/job/HK-ONE-ES-49F/Assistant-Vice-President_R004400",
    closeNote: "R004400 canApply true 9 Sep 19:50 UTC · official title Assistant Vice President · Equity Product Development",
    tier: "B",
    bands: ["capital", "institutions"],
    status: "live",
    pay: 4,
    security: 5,
    reputation: 5,
    balance: 3,
    fit: 3,
    rhyme: "Exchange-traded product. Market infrastructure with a product name.",
    rhymeZh: "交易所买卖产品。市场基建，带着产品的名字。",
    portalOnly: true,
    desk: {
      apply: "HKEXCareerPage R004400. Official slug HK-ONE-ES-49F / Assistant-Vice-President_R004400.",
      caution:
        "Sibling Group Strategy VP is B170 R004139-1 — do not spray both the same week. Old Group Strategy R004123 slug stays 404.",
    },
  },
  {
    id: "A25",
    rank: 29,
    title: "Manager, Investment (HK)",
    org: "The Mills Fabrica",
    location: "Hong Kong",
    href: "https://www.themillsfabrica.com/careers/manager-investment-hk/",
    closeNote: "Posted 29 Apr 2026",
    tier: "A",
    bands: ["cvc", "institutions"],
    status: "live",
    pay: 3,
    security: 3,
    reputation: 3,
    balance: 4,
    fit: 4,
    rhyme: "Climate/fashion CVC. Angel-adjacent. Do not email the general contact as if it were HR.",
    rhymeZh: "气候/时尚 CVC。贴近天使。不要把总邮箱当成 HR。",
    desk: {
      apply: "Listing only. contact@themillsfabrica.com is general contact, not a job-apply instruction.",
      caution: "Do not guess HR.",
    },
  },
  {
    id: "B165",
    rank: 99,
    title: "Vice President, Blackstone Multi-Asset Investing (BXMA) Asia",
    org: "Blackstone",
    location: "Hong Kong",
    href: "https://blackstone.wd1.myworkdayjobs.com/en-US/Blackstone_Careers/job/Hong-Kong/Blackstone-Multi-Asset-Investing--BXMA----Asia--Vice-President_45356",
    closeNote: "Workday 45356 · canApply true · posted 2 days · Absolute Return FoF",
    tier: "cvc",
    bands: ["capital", "stretch"],
    status: "skip",
    pay: 5,
    security: 3,
    reputation: 5,
    balance: 2,
    fit: 2,
    rhyme: "Hedge-fund allocator, not an AI product or CVC seat.",
    rhymeZh: "对冲基金配置，不是 AI 产品或 CVC 席。",
    skipWhy:
      "Official JD: 7–10+ years hedge fund industry, preferably Asia manager selection. Absolute Return LP investments. Fluent English and Mandarin. Not AI-native building. Skip vs Meitu B71 and Fidelity B19. Skip Talent Acquisition 45015. Skip Singapore PE IR Product 45127 vs HK seat.",
  },
  {
    id: "A0c",
    rank: 99,
    title: "Director (IT & System Development)",
    org: "HKMA / CMU OmniClear",
    location: "Hong Kong",
    href: "https://www.hkma.gov.hk/eng/about-us/join-us/current-vacancies/recruit-20260828-5/",
    closeAt: "2026-09-12T23:59:00+08:00",
    closeNote: "Sat 12 Sep 2026 · isolated official JD",
    tier: "A",
    bands: ["institutions", "stretch"],
    status: "skip",
    pay: 4,
    security: 5,
    reputation: 5,
    balance: 4,
    fit: 1,
    rhyme: "Custody-platform IT director. Not the product seat.",
    rhymeZh: "托管平台 IT 总监。不是产品席。",
    skipWhy:
      "Official JD: 8 years IT leadership including 3 years custody / fund administration / asset servicing; CS/IT degree; SWIFT/FIX/ISO 20022; SQL + Python/C#/Java; English + Chinese including Cantonese and Putonghua. Keep A0b Director, Product Development.",
  },
  {
    id: "A0d",
    rank: 99,
    title: "Executive Director (IT & System Development)",
    org: "HKMA / CMU OmniClear",
    location: "Hong Kong",
    href: "https://www.hkma.gov.hk/eng/about-us/join-us/current-vacancies/recruit-20260904-3/",
    closeAt: "2026-09-19T23:59:00+08:00",
    closeNote: "Fri 19 Sep 2026 · isolated official JD",
    tier: "A",
    bands: ["institutions", "stretch"],
    status: "skip",
    pay: 5,
    security: 5,
    reputation: 5,
    balance: 3,
    fit: 1,
    rhyme: "CTO-class FMI architecture. AI is a line on innovation, not the job.",
    rhymeZh: "金融基建的 CTO 级架构。AI 只是创新里的一行，不是这份工作。",
    skipWhy:
      "Official JD: 10 years IT leadership owning architectures and enterprise services; in-house team build; mainframe-to-modular; post-trade/custody domain; SWIFT and ICSD connectivity; Cantonese and Putonghua. Higher than Director IT. Keep A0b.",
  },
  {
    id: "A37",
    rank: 99,
    title: "Director of AI Infrastructure",
    org: "Cyberport",
    location: "Hong Kong",
    href: "https://www.cyberport.hk/en/news/career_opportunities/",
    closeAt: "2026-09-30T23:59:00+08:00",
    closeNote: "Ref DAI260819W · isolated official JD · 12–15-year GPU/HPC",
    tier: "A",
    bands: ["institutions", "stretch"],
    status: "skip",
    pay: 4,
    security: 5,
    reputation: 4,
    balance: 4,
    fit: 1,
    rhyme: "Supercomputing ops. Not a product or CVC seat.",
    rhymeZh: "超算运维。不是产品或 CVC 席。",
    skipWhy:
      "Official JD: 12–15 years IT / AI / HPC / GPU / cloud infrastructure; reports to CTO; CS/engineering degree; Kubernetes, CUDA, PyTorch. Less experience → Senior Manager. Keep A30 / B4. Keep A36 if public-mission strategy is the want.",
  },
  {
    id: "A38",
    rank: 99,
    title: "Head of Entrepreneurship",
    org: "Cyberport",
    location: "Hong Kong",
    href: "https://www.cyberport.hk/en/news/career_opportunities/",
    closeAt: "2026-09-30T23:59:00+08:00",
    closeNote: "Ref HOE260811W · isolated official JD · 15-year incubation + Cantonese",
    tier: "A",
    bands: ["institutions", "stretch"],
    status: "skip",
    pay: 4,
    security: 5,
    reputation: 4,
    balance: 4,
    fit: 2,
    rhyme: "Public incubator GM. The Director of Entrepreneurship seat is already named.",
    rhymeZh: "公共孵化器总经理。创业总监席已经有名字。",
    skipWhy:
      "Official JD: 15+ years startup incubation / venture building / entrepreneurship programme leadership; excellent command of Cantonese, Chinese and English. Wilson Chan already Director of Entrepreneurship since Apr 2026. Skip unless public incubator GM is the want. Keep A36.",
  },
  {
    id: "B167",
    rank: 99,
    title: "Director - Digital Currencies Commercialisation",
    org: "HSBC",
    location: "Central, Hong Kong",
    href: "https://apply.careers.hsbc.com/job/Central-Director-Digital-Currencies-Commercialisation-Hong/1370168557/",
    closeNote: "Phenom 1370168557 · official: position filled",
    tier: "B",
    bands: ["capital"],
    status: "skip",
    pay: 5,
    security: 5,
    reputation: 5,
    balance: 3,
    fit: 4,
    rhyme: "The director commercialisation desk filled. Keep the SPM if today is the clock.",
    rhymeZh: "数字货币商业化总监已满。今天的钟还在 SPM。",
    skipWhy:
      "Official Phenom 1370168557: Sorry, this position has been filled. Sibling Director DAC Settlement & Collaboration 1370170757 also filled. Keep B76 SPM Digital Currencies 1369854357 (validThrough Thu 10 Sep 16:00 UTC, 8 years wholesale payments, Mandarin an advantage). Skip Standard Chartered Head of CBDC and DA China 57782 until jobs.standardchartered.com is live (official: not available). Skip Goldman ACM ED 178896 — PWM alternatives capital raising, not AI-native. Skip Mastercard Agent Pay Greater China R-288096 (Singapore) and AI Strategic Partnerships R-289119 (San Francisco).",
  },
  {
    id: "B168",
    rank: 99,
    title: "Director - DAC Settlement and Collaboration",
    org: "HSBC",
    location: "Central, Hong Kong",
    href: "https://apply.careers.hsbc.com/job/Central-Director-Digital-Assets-and-Currencies-Settlement-and-Collaboration-Hong/1370170757/",
    closeNote: "Phenom 1370170757 · official: position filled",
    tier: "B",
    bands: ["capital"],
    status: "skip",
    pay: 5,
    security: 5,
    reputation: 5,
    balance: 3,
    fit: 3,
    rhyme: "Settlement director filled. Do not chase the LinkedIn post.",
    rhymeZh: "结算总监已满。不要追领英帖。",
    skipWhy: "Official Phenom: position filled. Keep B76. Do not email Lewis Lei Sun as if it were an apply channel.",
  },
  {
    id: "B169",
    rank: 99,
    title: "Product Manager - AI (Growth)",
    org: "Binance",
    location: "Hong Kong / Asia / Taiwan · Remote",
    href: "https://jobs.lever.co/binance/bc1302e3-f280-4550-ad1d-d51b7610e240",
    closeNote: "Official Lever · 5-year growth/fission PM",
    tier: "cvc",
    bands: ["cvc"],
    status: "skip",
    pay: 4,
    security: 2,
    reputation: 3,
    balance: 2,
    fit: 2,
    rhyme: "Growth hacking with an AI label. Keep the TradFi wealth seat.",
    rhymeZh: "增长黑客，贴着 AI 标签。守住传统金融财富席。",
    skipWhy:
      "Official Lever: 5 years user growth / growth hacking / PM; fission loops; Remote. Not a director desk. Keep B150 then optional B151. Skip Hang Seng Head of AI Adoption until an official Hang Seng Phenom URL exists (eFinancialCareers aggregator only; CTgoodjobs already expired). Skip Hang Seng Senior Manager Innovation & Ventures LinkedIn 4214290862 — LinkedIn no longer accepting; CTgoodjobs expired. Skip BlackRock Head of AI and Data Transformation GPS R263870 — San Francisco / New York, not Hong Kong. Skip AIA JR-67573-1 Data Analytics and AI vs B153/B117 (DS delivery, validThrough 30 Sep, still live). Skip HKU Research Officer AI and Industry Collaboration 537093 — closed 31 Aug 2026. Skip MTR Senior Manager AI & Digitalisation 250000Z1 — closed 9 Jul 2026. Skip Goldman PWM Talent Strategy VP 177373 — talent/HR, not AI-native. Skip Value Partners speculative career@vp.com.hk until an isolated JD exists. Skip Eastspring Director AI Research — filled Singapore 24 Aug 2026.",
  },
  {
    id: "B170",
    rank: 18,
    title: "Group Strategy, Vice President",
    titleZh: "集团策略副总裁",
    org: "HKEX",
    location: "Exchange Square, Hong Kong",
    href: "https://hkex.wd3.myworkdayjobs.com/HKEXCareerPage/job/HK-ONE-ES-50F/Group-Strategy--Vice-President_R004139-1",
    closeNote: "Workday R004139-1 · canApply true · posted 25 Jun 2026 · no endDate · 40-hour week",
    tier: "B",
    bands: ["institutions", "cvc", "stretch"],
    status: "live",
    pay: 4,
    security: 5,
    reputation: 5,
    balance: 4,
    fit: 3,
    rhyme: "Exchange strategy that also weighs investments and partnerships. Forty hours named. After Meitu if the market-infra CVC is the want.",
    rhymeZh: "交易所策略，也在称投资与合作。工时写了四十。美图之后，若市场基建 CVC 是想要的。",
    stretch: true,
    portalOnly: true,
    desk: {
      apply: "Official Workday hkex.wd3 HKEXCareerPage R004139-1. HK-ONE ES 50/F. canApply true.",
      draft: "r2545377456963307119",
      caution:
        "TA post prefers MBB — do not invent it. Official JD prefers strategy / corporate finance / exchanges, no numbered years. Sibling ETP is B40b. Skip Depository Solution & Transformation R004254 vs this Group Strategy seat. Old R004123 slug 404.",
    },
  },
  {
    id: "B171",
    rank: 13,
    title: "APAC Payments - Strategy - Executive Director",
    org: "JPMorganChase",
    location: "Kwun Tong, Hong Kong",
    href: "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/210739466",
    closeNote: "Oracle CX 210739466 · ExternalPostedStartDate 18 May 2026 · no endDate · Kwun Tong Quayside",
    tier: "B",
    bands: ["capital", "stretch"],
    status: "live",
    pay: 5,
    security: 4,
    reputation: 5,
    balance: 2,
    fit: 3,
    rhyme: "Wholesale payments strategy next to digital rails. Official at last. After the AI solution lead, if this is the payments desk.",
    rhymeZh: "批发支付策略，贴着数字轨道。官网终于到了。先 AI 方案负责人，若这才是支付席。",
    stretch: true,
    portalOnly: true,
    desk: {
      apply: "Official Oracle CX_1001 job/210739466. REST confirms HK. LinkedIn 4405870571 is a mirror.",
      draft: "r7906757809933544180",
      caution:
        "10+ years payments/banking/treasury + top-tier consulting or internal strategy. Do not invent MBB or a payments decade. Wrong id 210763531 was JS-empty. Skip sibling FIG Sales ED/MD. Skip Payments Industry Solutions VP until official CX.",
    },
  },
  {
    id: "B172",
    rank: 22,
    title: "Director, Strategic Change Initiative",
    org: "Standard Chartered",
    location: "Kowloon City, Hong Kong",
    href: "https://jobs.standardchartered.com/job/Director%2C-Strategic-Change-Initiative/60809-en_GB/",
    closeAt: "2026-09-30T23:59:00+08:00",
    closeNote: "Req 60809 · Band 5 · posting end 30 Sep 2026 · WRB Digital",
    tier: "B",
    bands: ["capital", "stretch"],
    status: "live",
    pay: 4,
    security: 4,
    reputation: 4,
    balance: 3,
    fit: 2,
    rhyme: "Digital-wealth change PMO. Not an AI product seat. After the AI solution lead if WRB change is the want.",
    rhymeZh: "数字财富变革 PMO。不是 AI 产品席。先 AI 方案负责人，若 WRB 变革是想要的。",
    stretch: true,
    portalOnly: true,
    desk: {
      apply: "Official jobs.standardchartered.com 60809. Kowloon City. Band 5.",
      draft: "r7566136181211083618",
      caution:
        "10+ years large-scale change. Do not invent SAFe/PMP/TOGAF. Skip 60894 Client Care Center PM (close 25 Sep). Skip Digital Engagement 48866 (ended 14 Jun). Skip Head of CBDC and DA China 57782 until that page is live.",
    },
  },
  {
    id: "A39",
    rank: 99,
    title: "Senior Manager, Partnerships",
    org: "HKSTP",
    location: "Island East, Hong Kong",
    href: "https://careers.hkstp.org/job/Island-East-Senior-Manager%2C-Partnerships-HK-H/1366226266/",
    closeNote: "Phenom 1366226266 · Job Code P893 · until filled · construction / Cantonese",
    tier: "A",
    bands: ["institutions", "stretch"],
    status: "skip",
    pay: 3,
    security: 5,
    reputation: 4,
    balance: 4,
    fit: 2,
    rhyme: "Construction partnerships with an I&T label. Keep the AI director.",
    rhymeZh: "建造业合作，贴着创科标签。守住 AI 总监席。",
    skipWhy:
      "Official JD: construction and built-environment executives; government works departments; 10 years preferably construction/entrepreneurship; English + Chinese including Cantonese and Putonghua. Keep A30 Director AI and Data 1366190466 and A1 Investor Engagement.",
  },
  {
    id: "B173",
    rank: 99,
    title: "Vice President – Depository - Solution & Transformation",
    org: "HKEX",
    location: "Hong Kong",
    href: "https://hkex.wd3.myworkdayjobs.com/HKEXCareerPage/job/HK-CMP-6F/Vice-President---Depository---Payment---Transformation_R004254",
    closeNote: "Workday R004254 · canApply true · posted 3 Aug 2026 · 12-year / 8-year ops stretch",
    tier: "B",
    bands: ["institutions", "stretch"],
    status: "skip",
    pay: 4,
    security: 5,
    reputation: 5,
    balance: 4,
    fit: 2,
    rhyme: "Post-trade ops with an AI line. Keep Group Strategy.",
    rhymeZh: "后交易运维，带着一行 AI。守住集团策略席。",
    skipWhy:
      "Official JD: 12 years including 8 years senior leadership in FS / market infrastructure / vault; fee and payment operations; AI/automation/chatbot as ops tools. Keep B170 Group Strategy R004139-1. Do not spray both. Skip Cyberport Chief Corporate Development Officer LinkedIn — Georgina Chu in seat since Feb 2024.",
  },
  {
    id: "A40",
    rank: 99,
    title: "Manager (Intellectual Property Management), KTEO",
    org: "PolyU",
    location: "Hung Hom, Hong Kong",
    href: "https://jobs.polyu.edu.hk/job_detail.php?job=260908015",
    closeAt: "2026-09-22T00:00:00+08:00",
    closeNote: "Consideration from 22 Sep 2026 until filled · official Apply Now · life-science IP",
    tier: "A",
    bands: ["institutions", "stretch"],
    status: "skip",
    pay: 3,
    security: 5,
    reputation: 5,
    balance: 5,
    fit: 1,
    rhyme: "Biotech patents, not entrepreneurship. Keep the incubation seat.",
    rhymeZh: "生命科学专利，不是创业台。守住孵化席。",
    skipWhy:
      "Official JD 260908015-IE: recognised degree in Life Science / Biomedical / Applied Biology; six years IP in biotech/pharma; English + Chinese with fluency in Cantonese and Putonghua. Keep A4 SM Entrepreneurship 260827002-IE. job.php?id=260908015-IE 404; working Apply URL is job_detail.php?job=260908015.",
  },
  {
    id: "A41",
    rank: 99,
    title: "Manager (Post-Investment Management), Office of SVP (Innovation and Enterprise)",
    org: "City University of Hong Kong",
    location: "Kowloon Tong, Hong Kong",
    href: "https://jobs1.cityu.edu.hk/apply/Default.aspx?jobtype=NACAD",
    closeNote: "Not on official NACAD 102-row dump 9 Sep 20:15 UTC · LinkedIn 4327341077 no longer accepting",
    tier: "A",
    bands: ["institutions", "cvc", "stretch"],
    status: "skip",
    pay: 3,
    security: 5,
    reputation: 5,
    balance: 4,
    fit: 4,
    rhyme: "Alma-mater angel fund that left the listing. Keep the CDTO door.",
    rhymeZh: "母校天使基金已经不在名单上。守住首席数字官那扇门。",
    skipWhy:
      "Official NACAD HTML dump of 102 administrative posts still has no Post-Investment Manager as of 9 Sep 21:00 UTC. LinkedIn 4327341077 no longer accepting. Aggregator jobhongkong24h (CFA or LL.M.; Cantonese and Putonghua; 8–10 years VC/PE) is stale. Keep A31 CDTO. Do not email hrojob@cityu.edu.hk.",
  },
  {
    id: "B175",
    rank: 99,
    title: "Head of Data and AI",
    org: "Zurich",
    location: "Hong Kong / Shenzhen",
    href: "https://www.careers.zurich.com/job/Hong-Kong-Head-of-Data-and-AI/1359113257/",
    closeNote: "Phenom 1359113257 · official no longer available 9 Sep 20:15 UTC",
    tier: "B",
    bands: ["capital", "stretch"],
    status: "skip",
    pay: 4,
    security: 4,
    reputation: 4,
    balance: 3,
    fit: 3,
    rhyme: "The head seat closed. Keep the brand AI product owner.",
    rhymeZh: "主管席关了。守住品牌 AI 产品负责人。",
    skipWhy:
      "Official careers.zurich.com Phenom 1359113257: no longer available for application. 15-year insurance + Cantonese and/or Mandarin were stretches anyway. Keep B33 Product Owner AI Brand & Marketing 1368805957 (confirm HK). Skip JPM AM AI Strategist 4063149377 and SAIGE VP 4370151959 (LinkedIn no longer accepting).",
  },
  {
    id: "B176",
    rank: 25,
    title: "Transformation Partner – AI Growth Initiatives Lead",
    org: "AIA",
    location: "Hong Kong / Macau",
    href: "https://aia.wd3.myworkdayjobs.com/en-US/External/job/Hong-Kong-HK-AIA-Hong-Kong--Macau/Transformation-Partner---AI-Growth-Initiatives-Lead_JR-67284",
    closeNote: "LinkedIn 4424879911 still listed · official CXS 404 this pass · watch",
    tier: "B",
    bands: ["capital", "stretch"],
    status: "watch",
    pay: 4,
    security: 4,
    reputation: 4,
    balance: 3,
    fit: 3,
    rhyme: "AI growth PMO at AIA. LinkedIn still talks. Official Workday has not confirmed canApply.",
    rhymeZh: "友邦的 AI 增长 PMO。领英还在说。官网还没有确认可以申请。",
    stretch: true,
    portalOnly: true,
    desk: {
      apply: "Watch only. Re-GET Workday CXS JR-67284 before ranking live. After B9b → B153 → B117 if it returns canApply true.",
      caution:
        "8 years insurance/FS. Official External search did not return JR-67284 this pass. HTML job URL 200 but CXS 404 again 9 Sep 21:00 UTC. Do not paste until canApply is proven. AXA Head of Data Science & AI is still LinkedIn-only — official careers.axa.com has DSM 9681 / Assistant 8701, not the Head. Do not email axa-talent-hub@axa.com.hk.",
    },
  },
  {
    id: "B178",
    rank: 27,
    title: "Director, Institutional Distribution & Partnerships",
    org: "Animoca Brands",
    location: "Hong Kong",
    href: "https://jobs.lever.co/animocabrands/dc6409fc-944d-4331-8019-dbd643ae1d90",
    closeNote: "Official Lever dc6409fc · NUVA · Hong Kong on-site · Apply live 9 Sep 20:05 UTC",
    tier: "cvc",
    bands: ["cvc", "capital", "stretch"],
    status: "live",
    pay: 4,
    security: 2,
    reputation: 3,
    balance: 2,
    fit: 3,
    rhyme: "Institutional distribution next to a 540-company book. Not a CVC cheque. After HashKey if FO coverage is the want.",
    rhymeZh: "机构分销，贴着五百四十家投资簿。不是 CVC 支票。先 HashKey，若家族办公室覆盖才是想要的。",
    stretch: true,
    portalOnly: true,
    desk: {
      apply: "Official Lever dc6409fc-944d-4331-8019-dbd643ae1d90. After HashKey 611 / OKX product if distribution not product is the want.",
      draft: "r1254277633540875993",
      caution:
        "8–10 years institutional sales/closed tickets at PB/tokenization/AM/trading. Do not invent closed LP tickets. Mandarin a plus; English essential; do not claim Cantonese. Skip China Merchants Capital MD PE LinkedIn — people already in seat. Skip Magic Compass / MC Group Head of AI Productivity LinkedIn 4457415399 — no longer accepting.",
    },
  },
  {
    id: "B179",
    rank: 99,
    title: "Head of AI Productivity & Governance",
    org: "Magic Compass / MC Group",
    location: "Hong Kong",
    href: "https://hk.linkedin.com/jobs/view/head-of-ai-productivity-governance-at-mc-group-4457415399",
    closeNote: "LinkedIn 4457415399 · no longer accepting 9 Sep 20:05 UTC",
    tier: "cvc",
    bands: ["cvc", "stretch"],
    status: "skip",
    pay: 4,
    security: 2,
    reputation: 2,
    balance: 3,
    fit: 4,
    rhyme: "The unnamed-firm pack closed on LinkedIn. Keep the licensed desks.",
    rhymeZh: "未具名公司那一包在领英关了。守住持牌台。",
    skipWhy:
      "LinkedIn no longer accepting. Recruiter is Magic Compass. King Deux / RH unnamed packs stay after APPROVE only. Keep HSBC B4 / OKX B177 / Meitu B71.",
  },
  {
    id: "B180",
    rank: 99,
    title: "Executive Director, Digital Product Solutions",
    org: "RGA",
    location: "Hong Kong",
    href: "https://www.rgarecareers.com/us/en/job/J27314/Executive-Director-Digital-Product-Solutions",
    closeNote: "Official rgarecareers.com J27314 · no longer posted 9 Sep 21:00 UTC",
    tier: "B",
    bands: ["capital", "stretch"],
    status: "skip",
    pay: 4,
    security: 4,
    reputation: 4,
    balance: 3,
    fit: 2,
    rhyme: "The reinsurance product desk left the official board. LinkedIn was late.",
    rhymeZh: "再保险产品席已经离开官网。领英来晚了。",
    stretch: true,
    skipWhy:
      "Official https://www.rgarecareers.com/us/en/job/J27314/Executive-Director-Digital-Product-Solutions: This position is no longer posted. LinkedIn 4407576665 is stale. 15-year consulting/transformation was a stretch anyway. Keep B4 / B33 / B163. Do not apply LinkedIn-only. Skip Cathay Head of Digital Transformation until careers.cathaypacific.com job URL is isolated.",
  },
  {
    id: "B181",
    rank: 22,
    title: "AI Lead (North Asia)",
    titleZh: "北亚人工智能负责人",
    org: "Alvarez & Marsal",
    location: "Central, Hong Kong",
    href: "https://careers.alvarezandmarsal.com/en/jobs/18010839-ai-lead-north-asia",
    closeNote: "Official HK board 18010839 · posted 6 Aug 2026 · isolated live 9 Sep 21:00 UTC",
    tier: "B",
    bands: ["capital"],
    status: "live",
    pay: 4,
    security: 3,
    reputation: 4,
    balance: 2,
    fit: 4,
    rhyme: "Internal Greater China LLM stack because Claude cannot sit there. After the bank AI lead if the builder desk is the want.",
    rhymeZh: "大中华内部大模型台，因为 Claude 坐不进去。先银行 AI 负责人，若建造席才是想要的。",
    portalOnly: true,
    desk: {
      apply: "Official careers.alvarezandmarsal.com Apply on 18010839. After B4. Confirm Central seat on the form.",
      draft: "r2304373048251726625",
      caution:
        "Hands-on regional LLM platform (Qwen / Kimi / GLM) and AI governance — do not invent an infrastructure-level fine-tuning decade. Do not email talentacquisition@alvarezandmarsal.com (resumes discarded). Skip sibling Director M&A / Cost Transformation. Skip Senior Manager Digital Product Owner until official JD years are isolated. Aggregator deadline 22 Aug is stale vs the official listing still live. Skip DBS Head of Digital Transformation IBG until official WD exists (Ramesh Sankar already Regional Head).",
    },
  },
  {
    id: "B182",
    rank: 29,
    title: "Head of Data Strategy",
    org: "Coface",
    location: "Hong Kong",
    href: "https://jobs.smartrecruiters.com/coface/744000146658409",
    closeNote: "SmartRecruiters 744000146658409 · published 1 Sep 2026 · Apply live 9 Sep 21:00 UTC",
    tier: "B",
    bands: ["capital", "stretch"],
    status: "live",
    pay: 4,
    security: 4,
    reputation: 3,
    balance: 4,
    fit: 2,
    rhyme: "Trade-credit data governance. Hybrid hours. After the bank AI lead only if the data desk is the want.",
    rhymeZh: "区域数据治理。混合工时。先银行 AI 负责人，若数据台才是想要的。",
    stretch: true,
    portalOnly: true,
    desk: {
      apply: "Official SmartRecruiters 744000146658409. After B4 only if regional data strategy is the want.",
      draft: "r-2925786890591065290",
      caution:
        "10+ years data strategy / analytics leadership on JD — do not invent a data-science degree or a numbered data-architecture decade. Not AI-native product and not a CVC cheque. Skip HKBU Knowledge Transfer Officer (Events and Marketing) Oracle 25260804 vs A34. Skip HKMU 26001FP (closed 13 Jul).",
    },
  },
  {
    id: "A42",
    rank: 99,
    title: "Assistant Director (Mainland Research Development) (OSI)",
    org: "Hong Kong Metropolitan University",
    location: "Kowloon City, Hong Kong",
    href: "https://hkmu.taleo.net/careersection/ex_full_time/jobapply.ftl?lang=en&job=26001FP",
    closeNote: "Taleo 26001FP · closed 13 Jul 2026, 11:59 p.m.",
    tier: "A",
    bands: ["institutions", "stretch"],
    status: "skip",
    pay: 3,
    security: 5,
    reputation: 4,
    balance: 4,
    fit: 2,
    rhyme: "The mainland-research director seat already closed. Keep the knowledge-transfer manager.",
    rhymeZh: "内地科研发展席已经关了。守住知识转移经理。",
    skipWhy:
      "Official close 13 July 2026. 15 years higher-education stretch. Keep A33 SM Knowledge Transfer 26001XV (closes 14 Sep). Do not email hrowww@hkmu.edu.hk.",
  },
  {
    id: "B183",
    rank: 99,
    title: "Head of HK AI",
    org: "HSBC",
    location: "Kowloon City, Hong Kong",
    href: "https://apply.careers.hsbc.com/job/Kowloon-City-Head-of-HK-AI-Kowl/1369156757/",
    closeNote: "Phenom 1369156757 · official filled 9 Sep 21:05 UTC",
    tier: "B",
    bands: ["capital"],
    status: "skip",
    pay: 5,
    security: 5,
    reputation: 5,
    balance: 3,
    fit: 4,
    rhyme: "The Hong Kong AI head seat filled. Keep the solution lead.",
    rhymeZh: "香港 AI 主管席满了。守住方案负责人。",
    skipWhy:
      "Official apply.careers.hsbc.com 1369156757: Sorry, this position has been filled. Keep B4 Senior AI Solution Lead 1330173757. Skip Guangzhou Head of AI Software Development 1356439457 and Singapore HSBC Life Head of Data, AI & Intelligence vs the HK gravity well.",
  },
  {
    id: "B184",
    rank: 25,
    title: "Head of Product",
    titleZh: "产品负责人",
    org: "Sentient Foundation",
    location: "Hong Kong / remote",
    href: "https://jobs.ashbyhq.com/sentient-foundation/d95ac1b9-8a1a-4a7a-9997-ff9a3b957e0e",
    closeNote: "Official Ashby d95ac1b9 · isListed true · HK applicant location · posted 26 Jul 2026 · no deadline",
    tier: "cvc",
    bands: ["cvc", "capital"],
    status: "live",
    pay: 4,
    security: 2,
    reputation: 3,
    balance: 3,
    fit: 5,
    rhyme: "Open AGI product that has to ship. After the exchange product seat if this is the builder desk.",
    rhymeZh: "开源 AGI 产品，必须做出来。先交易所产品席，若这才是建造台。",
    confirmSeat: true,
    portalOnly: true,
    desk: {
      apply: "Official Ashby d95ac1b9. Confirm Hong Kong on the form. After OKX B73; pick this or B177 or Bjak B186, not all the same week.",
      draft: "r-1128762593538257550",
      caution:
        "4+ years AI/ML or developer-platform product, including leading a product function. Do not invent a research-lab decade. Skip sibling Head of Open Source Ecosystem f1f59760 — no Hong Kong location. Skip Sentient APAC Director of Operations until official Ashby with HK. Skip CSC Holdings AI Fund Investment Director until an official cscholdings.com careers URL exists — do not email info@cscholdings.com. Skip HKU School of Innovation Lecturer 536821 vs A31/A4. Skip Binance AI Chatbot PM 4e1e4873 and PM AI Agent Harness 0a03c5e3 — IC, not director-class; keep OKX B73.",
    },
  },
  {
    id: "B185",
    rank: 99,
    title: "AI Fund — Investment Manager / Investment Director",
    org: "CSC Holdings Limited",
    location: "Wan Chai, Hong Kong",
    href: "https://hk.joblum.com/job/ai-fund-investment-manager-investment-director/4186784",
    closeNote: "Joblum aggregator 29 Jul 2026 · no official careers URL this pass",
    tier: "cvc",
    bands: ["cvc", "stretch"],
    status: "skip",
    pay: 4,
    security: 2,
    reputation: 2,
    balance: 3,
    fit: 4,
    rhyme: "An AI cheque on an aggregator. Wait for the company's own door.",
    rhymeZh: "AI 基金还在聚合站上。等公司自己的门。",
    skipWhy:
      "HKEX 235 exists, but this vacancy is Joblum-only. No official cscholdings.com Apply URL isolated. Do not email info@cscholdings.com as apply. Keep Meitu B71 / Tencent B72 / HashKey 611.",
  },
  {
    id: "B186",
    rank: 26,
    title: "CEO, AI Investing",
    titleZh: "人工智能投资首席执行官",
    org: "Bjak / ActAI",
    location: "Hong Kong / remote",
    href: "https://jobs.ashbyhq.com/bjakcareer/66aedc1a-753c-43e7-806a-3b21f64ce9fd",
    closeNote: "Official Ashby 66aedc1a · isListed true · HK · published 1 Sep 2026 · no deadline",
    tier: "cvc",
    bands: ["cvc", "capital"],
    status: "live",
    pay: 4,
    security: 2,
    reputation: 2,
    balance: 2,
    fit: 5,
    rhyme: "A consumer investing line that has to ship. After the exchange product seat if founding the book is the want.",
    rhymeZh: "消费投资产品线，必须做出来。先交易所产品席，若要自己开这一本账。",
    confirmSeat: true,
    portalOnly: true,
    desk: {
      apply: "Official Ashby 66aedc1a. Confirm Hong Kong on the form. After OKX B73; pick this or Sentient B184 or OKX B177, not all the same week.",
      draft: "r-4142603404519534271",
      caution:
        "SEA insurtech building ActAI. CEO-of-a-line, not a listed-bank C-suite. Do not invent a consumer-wealth P&L decade. Do not email a guessed Bjak HR inbox. Do not spray sibling CEO AI Finance / Neobank / Stockbroking, Business Unit Head, COO, or IC PM the same week. Skip HKSTP Head of Investment 1358259866 — application link no longer valid. Skip PolyU Manager IP 260908015-IE (life-science IP + Cantonese) vs A4/A21.",
    },
  },
  {
    id: "A43",
    rank: 99,
    title: "Head of Investment",
    org: "Hong Kong Science and Technology Parks Corporation",
    location: "Island East, Hong Kong",
    href: "https://careers.hkstp.org/job/Island-East-Head-of-Investment-HK-H/1358259866/",
    closeNote: "Phenom 1358259866 · application link no longer valid 9 Sep 21:40 UTC",
    tier: "A",
    bands: ["institutions", "cvc", "stretch"],
    status: "skip",
    pay: 4,
    security: 5,
    reputation: 4,
    balance: 3,
    fit: 3,
    rhyme: "The park's CVC head seat left the door. Keep the AI director.",
    rhymeZh: "园区 CVC 负责人那扇门关了。守住人工智能总监。",
    skipWhy:
      "Official careers.hkstp.org 1358259866: The job application link is no longer valid. Twenty-year VC / early-stage stretch anyway. Keep A30 Director AI and Data / A1 Manager Investor Engagement / Meitu B71.",
  },
  {
    id: "A44",
    rank: 99,
    title: "Manager (Intellectual Property Management), KTEO",
    org: "PolyU",
    location: "Hung Hom, Hong Kong",
    href: "https://jobs.polyu.edu.hk/job_detail.php?job=260908015",
    closeNote: "Official 260908015-IE · consideration from 22 Sep 2026 until filled · posted 8 Sep 2026",
    tier: "A",
    bands: ["institutions", "stretch"],
    status: "skip",
    pay: 3,
    security: 5,
    reputation: 5,
    balance: 5,
    fit: 1,
    rhyme: "A life-science IP desk that asks for Cantonese. Keep the entrepreneurship seat.",
    rhymeZh: "知识产权经理要生命科学与粤语。守住创业席。",
    skipWhy:
      "Official PolyU 260908015-IE is live, but the JD requires a Life Science / Biomedical / Applied Biology degree, six years biotech/pharma IP, and fluency in Cantonese and Putonghua. Do not claim Cantonese. Skip vs A4 SM Entrepreneurship 260827002 and A21 Director KTEO 260827012-IE.",
  },
];

export type FieldFilter = "all" | "today" | "institutions" | "capital" | "cvc" | "stretch";

export function inField(role: CareerRole, filter: FieldFilter, now = new Date()): boolean {
  if (role.status === "skip") return false;
  if (filter === "all") return true;
  if (filter === "today") {
    return role.bands.includes("today") && isOpen(role.closeAt, now);
  }
  return role.bands.includes(filter);
}

export function sortField(list: CareerRole[], now = new Date()): CareerRole[] {
  return [...list].sort((a, b) => {
    const ua = urgency(a.closeAt, now);
    const ub = urgency(b.closeAt, now);
    const order = { now: 0, soon: 1, week: 2, open: 3 };
    if (order[ua] !== order[ub]) return order[ua] - order[ub];
    if (a.tier === "ideal" && b.tier !== "ideal") return -1;
    if (b.tier === "ideal" && a.tier !== "ideal") return 1;
    const am = a.closeAt ? msUntil(a.closeAt, now) : Number.POSITIVE_INFINITY;
    const bm = b.closeAt ? msUntil(b.closeAt, now) : Number.POSITIVE_INFINITY;
    if (am !== bm) return am - bm;
    return a.rank - b.rank;
  });
}

export function nextMoves(now = new Date()): CareerRole[] {
  const open = roles.filter((r) => r.status === "live" && isOpen(r.closeAt, now));
  const today = sortField(
    open.filter((r) => r.bands.includes("today") || r.tier === "ideal"),
    now,
  );
  const rest = sortField(
    open.filter((r) => !today.includes(r)),
    now,
  );
  return [...today, ...rest].slice(0, 8);
}
